tvheadend/tvheadend

- src/descrambler/capmt.c
Use capmt_queue_msg() after connecting instead of direct write to socket.
Fixes a crash when the channel is played and oscam is restarted.
> capmt: network mode: fix a crash when oscam is restarted

- Makefile.hdhomerun
This upgrades the embedded libhdhomerun to version 20180327.
Please also apply to the release/4.2 branch.
> Upgrade to libhdhomerun_20180327

- src/webui/webui.c
This patch fixes two major problems of FreeBSD port of tvheadend:
1. very high CPU usage while streaming a recored program
2. unable to stream the recorded program beyond 128MB.
Unlike Linux sendfile(), FreeBSD sendfile() requires an explicit
file offset, and return value must be checked to catch any error
occurred. (i.e., closed connection)
Patch tested with the latest FreeBSD port of tvheadend-4.2.6.
> webui: fix http_serve_file() for FreeBSD

- src/dvr/dvr.h
- src/dvr/dvr_autorec.c
- src/webui/static/app/dvr.js
This allows users to specify specific seasons to record, season has to be >= min and <= max.
This isn't quite what was requested in bug: it wanted a concat of title,subtitle,summary,description to allow users to regex seasons to record. But that method I think would be slow and a bit error prone with the OTA scrapers. So, instead I added another min/max field to autorec.
For example min=5,max=5 will record only season 5.
Setting min=5,max=0 will record everything on season 5 or
later, which is useful if you've already seen seasons 1--4.
This can then be combined with the normal fulltext regex
such as "Simpsons"+minseason=12.
Fixes: #5176
> dvr: Add minseason and maxseason to autorec (#5176)

- src/dvr/dvr.h
- src/dvr/dvr_db.c
I've been running variants of this patch and I believe this fixes the issue.
With yesterday's async autorec reschedule we can enter the scenario where we have a recording on disk, the user updates an autorec which matches that entry on disk and which is broadcasting now. The dvr_entry ends up being created, scheduled to start immediately and an info logged. The recording timer callback then realizes it is a "semantic dup" so destroys the dvr_entry. This then causes the async logic to wait for its 60s quiescent timeout and re-check the autorecs one final time to ensure nothing new needs scheduling. However it then finds that the same programme is still being broadcast but has not been scheduled, so does it all again.
So, the logfile ends up with an entry every minute saying a recording is …
> dvr: Fix async autorec reschedule info message logging/looping

- src/webui/xmltv.c
For example:
`<category lang="en">Show / Game show</category>
<episode-num system="xmltv-ns">10/ . 1/ . /  </episode-num></programme>
`
It passes the DTD and looks right for the few entries I checked (Season a/b . Episode c/d . Part e/f).
However I noticed that my existing fields in the xmltv export (such as title) have an incorrect three letter lang code of "eng" instead of "en". I don't know if that's just my config or if xmltv spec has changed:
`<title lang="eng">The Big Bang Theory</title>`
"This 'lang' should be the two-letter code such as 'en' or
'fr_FR'.  Or you can just leave it out and let your reader take a
guess."
> xmltv: xmltv export should include episode num and genre (#4266)

- lib/py/tvh/htsmsg.py
- lib/py/tvh/htsp.py
- support/eitscrape_test.py
- support/htspmon
Python2 expires January 2020 (PEP373), so start update to support Python3, while maintaining support for Python2.
Main differences:
- print requires brackets
- string is bytes in python2 and unicode in python3 and can't be mixed with bytes
- need to use struct to more easily pack/unpack binary data
- need to convert socket data to bytearray to allow data extraction since ord not allowed
- import and exception lines needed changing
Tested via "htspmon -e" on python2 and python3 on the assumption that it sends data and unpacks lots of messages so should give good coverage of the python htsp changes.
I had an issue where some OTA stations send non-utf-8 data (probably iso-8859-1): previously we'd just pass it through whereas now we have to decode the bytes in to a charset for a string and it …
> Python3: Update to start supporting python3 (but remain compatible with python2)

- Makefile
- Makefile.ffmpeg
- support/patches/remove-invalid-pure_func-qualifiers.diff
- Patch for nasm taken from Fedora 28
- Added CFLAGS -Wno-stringop-truncation -Wno-stringop-overflow
- fdk-aac requires -fPIC to link properly
> Fix building with gcc 8

- src/dvr/dvr_rec.c
Previously we added the filename to the dvr_entry at the start of the
recording, but did not persist it. This meant that if tvheadend
crashed before the programme completed then we would leave a file on
disk which is not referenced by any recording, hence will never be
deleted.
So we persist after the file is created/stream opened. This entry then
has filename, stream info, and (actual) start time, but no (actual)
stop time. The entry is then updated with full details at completion.
I don't believe persisting early causes any knock-on issues since we've
already informed htsp that the recording exists, and Kodi (at least modern
version I have) seem to know it's a live recording and keep updating the
end time.
AFAICT, playback in Kodi (and from Tvheadend finished recordings) only
plays back …
> dvr: Persist dvr entry filename upon creation.

- Makefile
The clang compiler (v4, 2017) does not have the gcc8 options "-Wno-stringop-truncation -Wno-stringop-overflow", so enable them only for gcc.
I originally tried to make it a check in the configure script, but clang (annoyingly) seems to only flag unknown options as a warning saying it does not understand the option but carries on to compile the program, and so the configure thinks it _does_ support the flag.
```
echo 'int main(){}' > /tmp/hw.c && clang -c  -Wno-stringop-overflow  /tmp/hw.c  && echo $? && ls hw.o
warning: unknown warning option '-Wno-stringop-overflow'; did you mean '-Wno-shift-overflow'? [-Wunknown-warning-option]
1 warning generated.
0  <--exit status ok, despite unknown compile options
hw.o <--file generated
```
> gcc8: Only disable warning options for gcc.

- Makefile
- configure
- debian/rules
- support/configure.inc
Add options to Debian build rules and configure/Makefile to enable hardening.
I have had occasional crashes where the debug locals variables are bad, so I've added the compile options to do stack checking, and general hardening based on [https://wiki.debian.org/Hardening ](https://wiki.debian.org/Hardening). These options are enabled if the compiler supports the flags.
> Makefile + Debian build hardening

- src/epg.c
- src/main.c
The "--dump" option (to enable core dumps in /tmp) only worked on Linux due to the Linux-specific prctl. However, FreeBSD (and others) can core dump in the cwd if it is writable, so allow the "cd /tmp", but still log the warning that it's not supported since other system settings can prevent core dumps.
Also minor fix up of an && that should be || in epg.
> FreeBSD: allow core dump, plus minor epg assert fix

- configure
- src/trap.c
Although the existing backtrace works correctly on Linux, on
FreeBSD it frequently generates a backtrace with completely
wrong function names. (FreeBSD 11.2, current latest version).
For example, making htsp_build_dvrentry crash with SEGV, it
would either not generate a stacktrace or would generate a
backtrace of:
-pthread_sigmask
-pthread_getspecific
-service_remove_unseen
-htsp_get_subscription_status
-htsp_init
-tcp_server_done
-tvhthread_create.
...instead of the correct backtrace of:
-<signal>
-htsp_build_dvrentry
-htsp_method_async
-htsp_read_loop
-htsp_serve...
So on FreeBSD only, we use libunwind to generate the
backtrace and function names. We explicitly make
libunwind and libexecinfo mutually exclusive since
FreeBSD has both.
Line are logged similar to:
CRASH: …
> FreeBSD: Add libunwind trap support for FreeBSD only.

- src/webui/xmltv.c
Previously we'd output "4/ . 3/. /", but it was raised
on the forum that some clients can not handle
the omitted "total" number.
So we now output the simpler "4 . 3 ." instead.
Examples:
```
<episode-num system="xmltv-ns">2 . 24/25 .   </episode-num>
<episode-num system="xmltv-ns"> . 233 .   </episode-num>
<episode-num system="xmltv-ns">2/2 . 25 .   </episode-num>
<episode-num system="xmltv-ns">22/30 . 9/22 .   </episode-num>
```
> xmltv export: Use format "X" instead of "X/" for season/episode export.

- src/webui/static/app/dvr.js
- src/webui/static/app/epg.js
- src/webui/static/app/ext.css
We now display fanart (if available) on the background of the dvr
dialog. This fanart image is also displayed every ten seconds where
the existing image is displayed.
Tested with safari/firefox and it seems ok, but not great.  I could not get the images scaled nicely based on the center, but hopefully a bit more css will fix that and how to scale/zoom images will become more obvious once we have a proper fanart grabber and more fanart images to play with.
The main complication is that css does not directly support making images less visible, so I had to create three div elements, and make the image in its own layer, and then make that layer transparent.
I also have to fiddle with the z-index on the (existing) image otherwise hover stops working (for enlarging the image), presumably …
> ui: Add fanart background to dvr details dialog.

- src/epggrab.c
- src/epggrab.h
- src/epggrab/module.c
The "periodic save database" means that for xmltv you can
import your daily listings, crash, restart, and not have xmltv
data since the periodic epgdb timer has not elapsed.
So, add an option so the user can save the database after the
import has completed, assuming changes occurred.
This save is delayed by a couple of minutes in case the user
is importing from several different xmltv guides, in which case
the save occurs after the last import.
> xmltv: Add option to save epgdb after xmltv import.

- src/webui/static/app/dvr.js
Previously the background fanart could be too big for the dialog so we'd just get the middle bit of the image.
Now we use css to scale it using 'background-size: cover'.
This can make the image slightly exceed the dialog dimensions (and be cropped), compared to 'contain' which would leave space at the top/bottom to maintain aspect.
Using 'cover' seems better with the fanart I've seen so far.
Tested in FF and Safari.
> ui: Use background-size to scale background fanart to fit dvr dialog box.

- src/input/mpegts/satip/satip.c
https://tvheadend.org/issues/4244
As we discussed a while ago, the configuration should be different.
* The full mux should not be supported
* Along with it an increase of maximum pids is useful to open more channels (to interact with all adapters with comfort).
> Optimize default configuration of SAT>IP Triax TSS 400

- src/htsp_server.c
In pvr.hts, there's a bug raised that Tvheadend's credits/cast/keywords might be causing problems when doing a deserialize of the binary message (before the actual parsing of the message contents):
[https://github.com/kodi-pvr/pvr.hts/issues/378](https://github.com/kodi-pvr/pvr.hts/issues/378)
I've _not_ managed to reproduce the problem (and the code has been in since Sep 2017 in tvh and November for pvr.hts).
However, I noticed we could tidy the code to use the string_list_serialize function which does an additional check that the converted string list message is created before adding it to the out msg.
I don't think this is the cause of their problem since we should core dump if msg was somehow null after the conversion, but the additional check might be worthwhile.
Also removed extra …
> htsp: Tidy serialization of category and keyword.

- src/descrambler/cclient.c
The ecm init state should be set within the services for loop.
Fixes #5324
> cclient: fix crash on cc_remove_card

- src/descrambler/cclient.c
I believe this is missing on the previous commit!
> descrambler: reset 'changed' flag on cc_remove_card

- docs/markdown/faqs.md
the tvheadend no longer seems to like the = sign in the option 
--http_root /my/tvh/server (working)
--http_root=/my/tvh/server (doesnt work)
nginx config updated to include the Connection "upgrade" to deal with the WS: /comet/ws traffic
> updated nginx example

- src/dvr/dvr_db.c
Scenario: Complex scheduling enabled. Recording ok, then crash and restart. Partially recorded files are left on disk but dvr/log entry pointing to files can sometimes be destroyed.
So on restart the recording is not currently running, so we can find a
better recording (via complex scheduling option).
If there is a better recording later in the week,
that show will get preference (since complex recording states we don't
want a partial recording so prefer a later date for a full recording).
But, we used to destroy the dvr_entry, but this does not delete its
associated files so they would be left on disk as orphans/unreferenced
from any dvr/log file.
So now we also call delete to delete the files.
> dvr: delete partial files when replacing schedule after crash

- src/dvr/dvr.h
- src/dvr/dvr_config.c
- src/dvr/dvr_db.c
- src/htsp_server.c
- src/satip/server.c
- src/webui/webui.c
- src/webui/webui.h
Previously when watching a programme, the user usually has to then
manually delete the programme to recover disk space, or wait for its
retention to expire.
So we now add an option to Config->Recording->DVR Profile. This allows
the user to select time after watching to automatically delete the
recording (unless it is marked as "keep forever"). Default is disabled
(do not delete after playback).
For example, if the user specifies "2 days" then we'd delete the
recording two days after playback, even if the retention period is "3
months".
"Playback" can vary based on client. Some clients read and cache the
entire file before starting playback, so the file would be marked as
watched immediately. Other clients only buffer a small amount, so the
file will be marked as watched near the end of …
> dvr: Add option to automatically delete recording after playback.

- src/webui/static/app/ext-access.css
EPG events count is dark-gray so we can't see it with access theme.
>  webui: access theme - color correction for EPG count info

- src/webui/static/app/epg.js
The EPG screen serviced by FreeBSD port of tvheadend has two abnormal control
behaviors:
Reset All button makes the list empty
Typing and then deleting any search string also makes the list empty.
This patch fixes the symptoms above.
Patch tested with the latest FreeBSD port of tvheadend-4.2.7.
Changes since v1:
- call reset only if required
> webui: epg: fix compatibility issue for FreeBSD

- Makefile.webui
- src/access.h
- src/api/api_epg.c
- src/dvr/dvr_db.c
- src/webui/static/app/dvr.js
- src/webui/static/app/epg.js
- src/webui/static/app/epgevent.js
- src/webui/static/app/ext.css
- src/webui/static/app/tvheadend.js
This add a similar/alternative button to DVR and EPG info dialog boxes.
Repurposed the "show duplicated" button from DVR to display this "show alternatives" dialog box. This then allows the user to select episodes to record.
Main internal changes was splitting some logic in epg.js so it could be shared with the new dialog, create new file epgevents.js to display the dialog box.
In tvh, we return the sorted lists using shared code since the dialog uses a livegrid that needs remote sorting. Also some minor const fixups and fixup core dump where NULL ptr passed through.
> ui: show similar and alternative broadcasts (#5335, #5336)

- src/webui/static/app/dvr.js
- src/webui/static/app/ext.css
When the dvr info dialog has a lot of text it was overflowing on to the buttons in the bbar.
By changing the css, the text now generates a scrollbar so no longer overflows in to the bbar. The image does still overflow, but its opacity makes it less of an issue.
Image below shows the scrollbar on the right when the window was resized to make the text flow.
> ui: Enable scrollbar for dialog info, fixes #5405

- src/input/mpegts/tvhdhomerun/tvhdhomerun.c
I have a DVB-T hdhomerun which reports itself as model hdhomerun5_dvbt. When installing with the wizard it incorrectly assumes it is DVB-C. This fixes it.
> hdhomerun: auto detect DVB_T devices

- src/main.c
ERR_remove_thread_state has been the successor since version 1.0.0.
Fixes compilation without deprecated APIs on 1.0.0 and above.
> main: Replace deprecated ERR_remove_state

- src/api/api_epg.c
- src/epg.c
- src/epg.h
- src/webui/static/app/dvr.js
- src/webui/static/app/epg.js
Some broadcasts do not have series link, so the related showings dialog returned an empty list.
Now, if we have no series link then we do a query to find entries that match by title and return that list as related showings.
Also make epg/dvr info dialogs slightly larger to mitigate problems where translated strings were pushing the related showings buttons off the screen.
Fixes: #5402
> ui: make related showings use api_epg_grid if no series link, fixes #5402

- src/input/mpegts/satip/satip.c
Share config w/ Triax TSS 400 (similar board and fw).
Tested with Kathrein EXIP 4124 and EXIP 418.
> Kathrein EXIP: Add default config (SATIP)

- src/dvr/dvr_autorec.c
- src/webui/static/app/dvr.js
Autorec rule can have minseason/maxseason and minyear/maxyear. However, specials (such as Christmas specials) frequently don't have season/episode details.  But users could expect all "s5 or greater" to include the "s5 Christmas special".
So, we now only compare min/max season if it is available in the EPG. Similar for min/max year. If the EPG is missing the info then we allow the entry to be recorded.
Also added these four fields to the autorec grid as requested.
> dvr: autorec should only compare min season/year if it exists in EPG (fixes #5479)

- docs/property/pathname.md
- src/dvr/dvr_rec.c
Previously the $q format specifier would only output movies as:
tvmovies/title (yyyy).ts
However, a common alternative is to store each movie in its own sub-directory:
tvmovies/title1 (yyyy)/title1 (yyyy).ts
tvmovies/title2 (yyyy)/title2 (yyyy).ts
Similarly for episodes we output:
tvshows/title/title - SxxEyy.ts
But a common alternative is to have one directory per season:
tvshows/title/Season 1/title - S01Eyy.ts
tvshows/title/Season 2/title - S02Eyy.ts
So we now add a "$3q" to output these common alternatives, as requested in the forums.
[https://tvheadend.org/boards/5/topics/35778](https://tvheadend.org/boards/5/topics/35778)
Also add equivalent "$3Q" to output without the "genre" prefix i.e., without "tvshows/" or "tvmovies/".
I've put change against the original issue 4667 which …
> dvr: New format specifier for per-dir seasons and one movie per dir. (#4667)

- src/config.c
- src/config.h
- src/input/mpegts/tvhdhomerun/tvhdhomerun.c
- src/input/mpegts/tvhdhomerun/tvhdhomerun_frontend.c
tvheadend relies on multicasting to communicate with the HDHomerun.
This presents problems when running tvheadend in a Docker container without enabling host networking in the container.
To solve this, I added 3 fields to the config -
1. hdhomerun_ip
2. local_ip
3. local_port
hdhomerun_ip is used during the discovery process. The IP of the HDHomerun device is passed to libhdhomerun, bypassing the multicast process.
local_ip and local_port are used for communications with the HDHomerun device. This lets you forward traffic from the Docker host to the container.
> Changes to make tvheadend work in a container while talking to HDHomerun

- Makefile.ffmpeg
Compiling master on Ubuntu 18.04 and 18.10 with vaapi enabled causes an error (as described in https://tvheadend.org/issues/5504).
```
/usr/bin/ld: /root/tvheadend/build.linux/ffmpeg/build/ffmpeg/lib/libavutil.a(hwcontext_vaapi.o): undefined reference to symbol 'XDisplayName'
//usr/lib/x86_64-linux-gnu/libX11.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:709: recipe for target '/root/tvheadend/build.linux/tvheadend' failed
make2: * [/root/tvheadend/build.linux/tvheadend] Error 1
make2: Leaving directory '/root/tvheadend'
debian/rules:15: recipe for target 'override_dh_auto_build' failed
make1: [override_dh_auto_build] Error 2
make1: Leaving directory '/root/tvheadend'
debian/rules:6: recipe for target 'build' failed
make: ** …
```
> Update to newest ffmpeg to fix libX11 compile issue when vaapi is enabled.

- src/httpc.c
- src/main.c
I'm cross-compiling release/4.2 for OpenWrt (and in their master, they're using OpenSSL 1.1.1b) and even tvheadend version 4.2.8 was tagged on 12th January 2019, there wasn't included PR https://github.com/tvheadend/tvheadend/pull/1217 , which was merged on 21st November 2018. Would be nice to have it included in the next stable version.
When I have included all the commits from @neheb, I have been able to successfully compile it. I will test it later on my router.
Otherwise release/4.2 (together with tagged version 4.2.8) ends up with output:
```
cc1: note: someone does not honour COPTS correctly, passed 2 times
src/main.c: In function 'main':
src/main.c:1356:3: error: implicit declaration of function 'ENGINE_cleanup'; did you mean 'EVP_PBE_cleanup'? …
```
> [4.2 release] Fix compilation with OpenSSL 1.1.1

- src/epggrab/support/freesat_huffman.c
Bug #5366 reported control codes appearing in EPG data on UK Freeview; this was fixed in commit 3ae6d947a4d074b3498e59f82d5a860273b0ae7f. However the same issue affects DVB-T2 channels where the EPG is Huffman coded.
freesat_huffman.c already has code to suppress these control codes, however the decoding is stopped when one is encountered and so the text is truncated. This patch drops the control codes but continues to decode the remaining text.
> Freesat_huffman: Suppress characters < 0x20 except \n.

- support/tvhmeta
The text returned from the server is utf-8 so needs an explicit
decode otherwise it defaults to ASCII and fails for programmes
with non-ASCII titles.
> fanart: Fix decode error for non-ASCII data

- src/input/mpegts/en50221/en50221_apps.c
Fix several issues in the en50221 menu text handling code that prevented the CAM messages from being passed on and then logged by linuxdvb_ca.c.
> Fix en50221 menu text handling

- Makefile
Only compilation follows './configure --disable-pie', linking instead
doesn't, because '-pie' flag is passed to LDFLAGS uncoditionally.
So add '-pie' flag only if CONFIG_PIE=yes.
Signed-off-by: Giulio Benetti <giulio.benetti@micronovasrl.com>
> Makefile: fix -pie linking according to --disable-pie

- src/input/mpegts/tvhdhomerun/tvhdhomerun.c
They renamed the symbol that was used to determine whether the
"hdhomerun_discover_find_devices_custom" needed to be aliased,
causing an FTBFS.  Instead, recognize both the old and new symbols.
> Fix compilation with libhdhomerun 20190621

- src/input/mpegts/linuxdvb/linuxdvb_frontend.c
Fix unknown signal and device status (HTSP Client) in the first 26 minutes after power on.
Incompatible values were compared:
time() = now = 1561843153 [s]
mclk() = uptime [μs]
https://github.com/tvheadend/tvheadend/blob/453ee8dfd80b240e1005502c002bdc6de3f121c8/src/input/mpegts/linuxdvb/linuxdvb_frontend.c#L2024-L2030
https://github.com/tvheadend/tvheadend/blob/453ee8dfd80b240e1005502c002bdc6de3f121c8/src/input/mpegts/linuxdvb/linuxdvb_frontend.c#L998-L1007
Patch tested with CoreELEC 9.0.x (devel) + Kodi 18.3 + Tvheadend HTSP Client 4.4.18.1 + Tvheadend Server 4.2.7.
> linuxdvb: fix signal status monitor

- src/main.c
- src/tvh_locale.c
- src/tvhlog.c
Fixes build error with uClibc: https://www.tvheadend.org/issues/5667
> Include stdio.h before tvheadend headers

- src/dvr/dvr_db.c
"record if different episode number" doesn't work as expected in the master branch:  https://tvheadend.org/issues/5632
With this modification, the season will be taken into account, as it was before, in order to determine if two episodes have different episode number or not.
> bugfix for autorecs duplicate episode number detection in autorecs

- .doozer.json
- Autobuild/raspbianbuster-armhf.sh
Please also cherry pick 2d020e8f214c6817f6b36271d82039c95a7d1447 for release/4.2, note these builds will fail until @andoma has a chance to add the required buildenv to doozer.io
> autobuild: add build target for raspbian-buster

- docs/property/htsp_output_format.md
- docs/property/xmltv_output_format.md
- src/access.c
- src/access.h
- src/channels.c
- src/channels.h
- src/htsp_server.c
- src/webui/static/app/acleditor.js
- src/webui/xmltv.c
Requested in the forums.  https://tvheadend.org/boards/12/topics/37170
Some TVs have limited xmltv support, have very limited memory and don't support description or other large text fields. So, add an enum to the user to choose a basic format to reduce memory usage on clients. This will strip many large text fields.
I also changed the xmltv to never output 'lang="xyz"' fields if there is only one language. This reduces the file size.
I also added the "basic fields" support to htsp. However I'm happy to re-deliver without that commit if it's not that useful.
Many of the changes are just whitespace or splitting the basic/normal output in to a separate function.
I don't use the features, but Saen has been testing the xmltv for a couple of weeks.
> xmltv: limit epg details for low memory devices, fixes #5630

- Makefile.hdhomerun
- support/patches/hdhomerun.diff
Allows to static build HDHomerun library when cross-compiling for other platforms (such as armel), see feature #5130.
The HDHomerun [Makefile ignores the `CC` variable](https://github.com/Silicondust/libhdhomerun/blob/9719cbc7a562dfc3ae638ba1f3769f9451db5389/Makefile#L14-L15) set by the TVHeadend makefile after configuration and this builds the `libhdhomerun.a` library with the host gcc (x86_64 for example). This gives errors when linking at the end:
```
Markdown: docs/wizard/network.md
Markdown: docs/wizard/status.md
CC              src/docs.o
CC              build.o
CC              timestamp.o
CC              tvheadend
/root/tvheadend/tvheadend/build.linux/hdhomerun/libhdhomerun/libhdhomerun.a: error adding symbols: File format not recognized
collect2: error: ld returned 1 exit status …
```
> Added patch to HDHomerun library to allow cross-compilation

- src/descrambler/tvhcsa.c
Fixes uclibc build error:
CC              src/descrambler/tvhcsa.o
In file included from /home/buildroot/autobuild/instance-0/output/build/tvheadend-8f1de1621d78c91431238176bf4f6290870a031a/src/tvhlog.h:30:0,
from src/descrambler/tvhcsa.h:30,
from src/descrambler/tvhcsa.c:19:
/home/buildroot/autobuild/instance-0/output/build/tvheadend-8f1de1621d78c91431238176bf4f6290870a031a/src/tvh_thread.h:163:25:
error: unknown type name '__do_not_use_pthread_mutex_t'
#define pthread_mutex_t __do_not_use_pthread_mutex_t
detected by buildroot autobuilder:
http://autobuild.buildroot.net/results/627/627e7080e655005d6724b9977670cc73059d6281/
> tvhcsa.c: include stdio.h

- src/input/mpegts/mpegts_mux.c
Should not it be the opposite?
`2019-03-28 00:28:53.648 mpegts: 498MHz in A - scan timed out (9/6 tables)`
>  Mux scan: Log correction

- src/transcoding/codec/codecs/libs/vaapi.c
After this change picture quality is very good from the first second on with av-lib and vaapi transcoding (h.264 / hevc). 
See Tickets:
https://tvheadend.org/issues/5607
https://tvheadend.org/issues/5701
> Fixed bad quality for vaapi transcoding h264 and hevc with bitrate #5607

- debian/tvheadend.postrm
Partial fix for https://tvheadend.org/issues/5705
`dh` replaces this placeholder with things it needs to add. Currently, postinst has this and is what installs, enables and starts the service, but postrm is missing it so files get left behind.
I haven't done anything about the home directory getting left behind because I'm not 100% sure that's safe to remove.
Please also add this to the 4.2 release branch
> packaging: add missing DEBHELPER placeholder to postrm script

- configure
In case the checks are compiled with CFLAGS including "-O1 -flto" (or any
other optimization level), a "test()" function not referenced by by main
will be optimized away and discarded prior to the final linking step, and
there will be no undefined symbols, thus the checks always succeeds.
This at least affects the "strlcpy"/"strlcat" checks, but may affects other
checks as well.
> Avoid configure checks being optimized away with LTO

- src/input/mpegts/iptv/iptv_private.h
- src/input/mpegts/linuxdvb/linuxdvb_private.h
The time_t items are used in expressions with int64_t mclk().
https://github.com/tvheadend/tvheadend/blob/6be300c430ab614aa527ef34e34f007f34a68ee0/src/input/mpegts/linuxdvb/linuxdvb_frontend.c#L998-L1007
https://github.com/tvheadend/tvheadend/blob/2c35dca60d373f685fad040b993450ed5505a546/src/input/mpegts/iptv/iptv_pipe.c#L112-L115
> mpegts: linuxdvb/iptv: fix integer overflow on 32-bit platforms

- src/api/api_mpegts.c
Lines were added commented waiting for "network enable/disable" to be implemented.
When it got implemented they were left behind.
PS: Should also make the "Services" tab rendering faster for "hide: parent disabled" since it will exit the loop as soon as it sees that the network is disabled (instead of unnecessary cycling through all the network muxes).
> mux grid: enable 'hide: parent disabled'

- src/webui/xmltv.c
See: http://xml.coverpages.org/XMLTV-DTD-20021210.html
> xmltv: Fix xmltv_ns typo, fixes #5720

- src/webui/static/app/epg.js
When using the WebUI and clicking a program in the EPG to bring up the "Broadcast Details" window, there is a IMDB icon at the bottom left of this window.  I find it very useful to directly query the IMDB website for the title I'm looking at.  Unfortunately, there was probably a change on IMDB side that generates a "Privacy error" message when trying to open the URL: https://akas.imdb.com/find?q=Skyfall 
Note: full URL example is given using the Skyvall movie title.
```
Your connection is not private
Attackers might be trying to steal your information from akas.imdb.com (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_COMMON_NAME_INVALID
```
This PR corrects this issue by providing an updated URL that works without issue to query a title.
The new URL I propose …
> WebUI: Fix the query URL for IMDB website

- src/dvr/dvr_db.c
- src/htsp_server.c
Expose recording file size over HTSP.
Needed to support this Kodi 19 feature: https://github.com/xbmc/xbmc/pull/17538
> HTSP v35: Add support for recording file size

- Makefile.ffmpeg
- Updated x264 to its the latest snapshot 20191216 as their
snapshotting service was discontinued.
- Updated x265 to version 3.2.
- Updated libvpx to version 1.8.2.
- Updated libogg to version 1.3.4
- Updated fdk-aac to version 0.1.6
There is version 2.0.x, but let's leave it for later.
- Updated opus to version 1.3.1
- Updated nv-codec-headers to version 8.2.15.10
- Updated ffmpeg to version 4.1.5
Fixes CVEs:
CVE-2019-9718
CVE-2019-9721
CVE-2019-11338
CVE-2019-11339
CVE-2019-12730
CVE-2019-17539
CVE-2019-17542
Misc changes:
- Changed url for libogg, libtheora, libvorbis to use HTTPS and previous
site points to new one
- FFmpeg now uses HTTPS
> Makefile.ffmpeg: update almost all upstream packages

- src/input/mpegts/dvb_psi.c
Not sure if this is entirely correct but otherwise you get:
```
src/input/mpegts/dvb_psi.c: In function ‘psi_tables_install’:
src/input/mpegts/dvb_psi.c:2334:41: error: ‘dvb_mux_dvbc_class’ undeclared (first use in this function)
2334 |     if (idnode_is_instance(&mm->mm_id, &dvb_mux_dvbc_class))
|                                         ^~~~~~~~~~~~~~~~~~
src/input/mpegts/dvb_psi.c:2334:41: note: each undeclared identifier is reported only once for each function it appears in
make: *** [Makefile:716: /var/tmp/portage/media-tv/tvheadend-9999/work/tvheadend-9999/build.linux/src/input/mpegts/dvb_psi.o] Error 1
```
> dvbpsi: Fix build when DVB is not enabled at all

- debian/tvheadend.service
- man/tvheadend.1
- rpm/tvheadend.service
- src/main.c
Hello following [FSH3](http://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05s13.html) consider to change default pid path to /run/tvheadend.pid from /var/run/tvheadend.pid.
Some utilities (i.e. systemd-analyze) are now reporting *legacy path* /var/run
`systemd-analyze verify tvheadend.service`
> /usr/lib/systemd/system/tvheadend.service:13: PIDFile= references a path below legacy directory /var/run/, updating /var/run/tvheadend.pid → /run/tvheadend.pid; please update the unit file accordingly.
> Consider to change default PID path to /run/tvheadend.pid

- src/epggrab/module/eit.c
Fixes a logic issue which resulted in an infinite busy loop when TVH encountered certain invalid EIT data.
In case the if condition inside the loop does not evaluate to true the variable in the loop condition (len) doesn't get touched and thus gets stuck inside the loop endlessly evaluating the same if and loop conditions. This patch makes it return an error instead of indefinitely looping.
> Fix infinite loop when parsing invalid EIT CRID data

- src/webui/xmltv.c
Adds support for exporting program icons. This has been supported when importing xmltv files but is not supported in the exported xmltv.
The fix is very simple, but if needed the pull request can be updated with additional flags to enable/disable this behaviour.
> xmltv: add program icon to exported xmltv. Fixes: #5685

- src/parsers/message.c
- src/parsers/parsers.c
- src/parsers/parsers.h
Seems to works for me in most cases, but i'm not sure if function parser_create is the best place to send pkt from rstlog.
Can someone test and review this patch ?
> Add packet buffer on stream restart, fixes #5722

- src/dvr/dvr_db.c
- src/htsp_server.c
Reverts tvheadend/tvheadend#1332 as dataSize is already a property.
> Revert "HTSP v35: Add support for recording file size"

- src/webui/html.c
It seems the escaping for html is using "`&quote;`" instead of "`&quot;`".
For example S3.2.4:
https://www.w3.org/MarkUp/html-spec/html-spec.txt
or
https://dev.w3.org/html5/html-author/charref
The browsers I tested displayed '&quote;' as double quote marks followed by "e;".
> Fix escape code '&quote;' should be '&quot;'.

- support/tvhmeta
Ased in operator instead.
Also, added check for empty string.
Signed-off-by: Christian Eiden <christian@eiden.ch>
> in python 3, dict.has_key() has been removed

- src/descrambler/capmt.c
There is a small typo in src/descrambler/capmt.c.
Should read `separately` rather than `seperately`.
> docs: fix simple typo, seperately -> separately

- configure
This change removes the dependency for the libva-x11 from the tvheadend build.
The libva-x11 library can cause issue when running TvHeadend in a headless server and the installation of several unnecessary packages. Running headless is the major use case for TvHeadend.
> Remove libva-x11 dependency

- src/tvh_thread.h
Fixes possible deadlock when using tvh_mutex_trylock() macro in thread non-debug mode.
The macro expands to call pthread_mutex_lock() instead of pthread_mutex_trylock(),
which most likely is a result of copy/paste.
> Fix possible deadlock when using tvh_mutex_trylock()

- Makefile.hdhomerun
There is a new version of libhdhomerun on the home page (also available under Fedora 32, 33)
> Upgrade to libhdhomerun_20200907

- src/transcoding/codec/codecs/libs/vaapi.c
- src/transcoding/transcode/hwaccels/vaapi.c
- remove "Baseline" h264 Profil (not exist)
- include "Main10" and "Rext" in hevc Profiles
> fix vaapi-profiles

- src/input/mpegts/tvhdhomerun/tvhdhomerun.c
- src/input/mpegts/tvhdhomerun/tvhdhomerun.h
- src/input/mpegts/tvhdhomerun/tvhdhomerun_frontend.c
Adding support to the HDHomeRun client for HDHomeRub device HDHR4-2IS which is compatible with ISDB-T standard used in Brazil and other countries.
> Add ISDB-T support to HDHomeRun client

- src/channels.c
- src/channels.h
- src/htsp_server.c
- src/http.h
- src/input/mpegts/iptv/iptv.c
- src/input/mpegts/iptv/iptv_mux.c
- src/input/mpegts/iptv/iptv_private.h
- src/input/mpegts/iptv/iptv_rtcp.c
- src/input/mpegts/iptv/iptv_rtcp.h
- src/input/mpegts/iptv/iptv_rtsp.c
- src/input/mpegts/iptv/iptv_udp.c
- src/plumbing/tsfix.c
- src/profile.c
- src/profile.h
- src/rtsp.c
- src/streaming.c
- src/streaming.h
Dear all,
Attached some new features I implemented for IPTV. Looking forward to your comments.
- Implement RTCP Negative Acknowledge (a.k.a. Retransmission) support for RTP streams.
When packet loss is detected the client will send a RTCP Generic Feedback report to the server. The server can than resend these lost packets.
Retransmitted packets are send through a second connection or as part of the main stream, both cases are supported.
For Multicast manual setup of the RTCP server is required, for RTSP automatic setup (was already implemented for Receiver Reports) or manual override is possible.
- General clean-up of unused RTCP code and restructure to allow for easy implementation of different types of RTCP messages.
- Make RTCP Receiver Reports optional.
- RTSP start session with …
> iptv: new features for multicast, rtsp & rtcp (retransmission & remote time shift)

- src/input/mpegts/iptv/iptv_private.h
- src/input/mpegts/iptv/iptv_rtcp.c
- src/input/mpegts/iptv/iptv_rtsp.c
- src/input/mpegts/iptv/iptv_udp.c
- src/plumbing/tsfix.c
- src/profile.c
- src/streaming.c
In case multiple users subscribe to a remote time shift channel the different code path would not initialize the service_t * sm_s properly and caused a segfault due to invalid pointer later in the code. Also I was able to revert the change from malloc to calloc, we need speed!
Furthermore the code was cleaned up slightly.
A limitation still is that all subscribers will look at the same source stream so remote time shifting will apply to all. A solution would be to spawn multiple instances of the same mux / service. Not sure how to handle this in tvheadend, it doesn't seem to be designed for this. Ideas are welcome!
> remote timeshift: fix crash on multiple subscriptions and cleanup

- src/profile.c
Will fix compilation with --enable-timeshift and --disable-iptv.
> remote timeshift: fix compilation with IPTV disabled

- debian/tvheadend.init
So that for systemd users, systemd-sysv-generator can work out where the pid file is located. And restart on detection that the process has died.
> Add pid file hint for systemd-sysv-generator

- src/esfilter.h
- src/esstream.h
- src/htsp_server.c
- src/input/mpegts/dvb_psi_pmt.c
- src/input/mpegts/dvb_psi_pmt.h
- src/parsers/parsers.c
- src/streaming.c
Motivation: https://forum.kodi.tv/showthread.php?tid=336682&pid=3052210#pid3052210
This brings back RDS data for SWR, WDR, hr, SR in Kodi and allows other tvh clients to handle RDS data contained in private stream with id 0x89.
Thanks to @carsten-gross for figuring out the details.
Second commit exposes the information, that an audio stream contains RDS data via HTSP.
> Add support for SCT_RDS, expose RDS flag via HTSP

- src/access.c
The conversion from unsigned long to long long is not necessary.
Corrected the print statement uses the format code %lu.
> Remove unnecessary conversion

- src/access.c
Reverts tvheadend/tvheadend#1408
> Revert "Remove unnecessary conversion" as the datatype is wrong

- src/epggrab/module/opentv.c
Events within the OpenTV SkyUK data can contain the same Event ID as another event on a different channel.
This results in missing or incorrect summary data in Tvheadend, since it's matching is based solely on the Event ID.
For example:
Notice how several events have the wrong summary, and others are missing a summary (since that summary was incorrectly linked to a different event).
To help illustrate, I found the Event ID for the event highlighted in the above screenshot and using a forked version of the [openTVtoXML external scraper](https://github.com/dave-p/openTVtoXML) (modified to also output Event IDs) I found all events with that same event ID.
<details>
<summary><b>Expand here to show full XML for those events</b></summary>
```
<programme start="20210929163000 +0100" …
```
> opentv: fix incorrect summaries for skyuk epg, fixes #5995

- src/epggrab/module/opentv.c
This fixes an issue whereby chunks of events within the OpenTV data can contain blank summaries following a re-scrape as shown below:
Prior to this scrape, the guide data in this section was complete including the summary data. 
On debugging the issue, I could see that both halves of the record (title and summary) were processed for these events, so something was going wrong in the matching or merging of this data.
<details>
<summary>Expand here for debug log extracts to go with the first screenshot above (re-scrape)</summary>
**Notice that the summary records were processed first.**
```
2021-10-19 15:05:28.266 [  DEBUG]:opentv: find by ch 609000000 eid 2965 = 0x7f0c68178390
2021-10-19 15:05:28.266 [  DEBUG]:opentv:   summary 'Beat the Drum, Catboy: Night Ninja plans to turn the daytime …
```
> opentv: fix missing summary data on rescrape, #5995

- src/input/mpegts/scanfile.c
When parsing pre-defined muxes in the w_scan format, only one gets added and its frequency is 0MHz.
```
2021-11-12 15:18:14.867 [  TRACE]:scanfile: load file /ca-test-test (processed bytes 5334453)
2021-11-12 15:20:44.977 [  TRACE]:scanfile: [A 473000000     8VSB] OK
2021-11-12 15:22:29.084 [  TRACE]:scanfile: [A 485000000     8VSB] OK
2021-11-12 15:22:33.810 [  TRACE]:scanfile: [A 491000000     8VSB] OK
2021-11-12 15:22:34.496 [  TRACE]:scanfile: [A 497000000     8VSB] OK
2021-11-12 15:22:35.116 [  TRACE]:scanfile: [A 503000000     8VSB] OK
2021-11-12 15:22:35.763 [  TRACE]:scanfile: [A 509000000     8VSB] OK
2021-11-12 15:22:36.362 [  TRACE]:scanfile: [A 521000000     8VSB] OK
2021-11-12 15:22:36.968 [  TRACE]:scanfile: [A 533000000     8VSB] OK
2021-11-12 15:22:37.574 [ …
```
> Fixed parsing pre-defined muxes in w_scan format

- src/utils.c
And return -ENAMETOOLONG if the string overflowed.  This fixes the
FTBFS on s390x with recent glibc/gcc versions.
This fixes #5949.
> Check the return code of snprintf in utils.c:rmtree

- configure
Add execinfo option to allow the user to disable the feature even if `execinfo.h` is found on the system
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
> configure: add execinfo option

- src/transcoding/codec/codecs/libs/nvenc.c
Commit 0165f365cd58bbcc3734e4ec9ce696b42870ff8e introduced an FTBFS
when -Werror=misleading-indentation is passed to the compiler.  It
appears from changes elsewhere in the file (around line 450) that
the "Set Defaults" statements were not intended to be included in
the if block, so this commit reformats it to make that obvious (and
also add curlybrackets as was done around 450.)
> nvenc: Fix Werror=misleading-indentation FTBFS

- src/transcoding/codec/codecs/libs/nvenc.c
Commit 0165f365cd58bbcc3734e4ec9ce696b42870ff8e introduced an FTBFS
when -Werror=int-conversion is passed to the compiler.  For
reasons unknown to me, the "value" argument to AV_DICT_SET_INT was
written as a string (const char *) rather than the int64_t that
the function behind the macro was expecting in the "Set Defaults"
statements.  This was resulting in the value of the pointer to the
character array getting used as the argument rather than the
integer itself, which appears to be what was intended.  This
triggers the Werror=int-conversion error and also probably results
in unexpected behavior from passing the pointer values.
> nvenc: Fix Werror=int-conversion FTBFS (and likely bug)

- .doozer.json
Hi!
I'm going to attempt and get tvheadend on Doozer to build against the newer Fedora versions. As I'm currently upgrading my system from Fedora 33 to 34, I'm not online on IRC, but you can usually ping me (rubdos) to take a further look.
In this first patch, I'm only changing out the version numbers. I don't expect anything weird to happen, but if it stops building from there on, you can expect further PRs.
I tried signing the CLA, but the page at https://www.clahub.com/agreements/tvheadend/tvheadend is blank on my browser.
Best,
Ruben
> Doozer: build for Fedora 34 and 35

- lib/py/tvh/tv_meta_tmdb.py
- lib/py/tvh/tv_meta_tvdb.py
- support/tvhmeta
RPM build currently gives these (e.g. https://doozer.io/tvheadend/tvheadend/buildlog/23860):
```
*** ERROR: ambiguous python shebang in /usr/bin/tv_meta_tvdb.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
*** ERROR: ambiguous python shebang in /usr/bin/tv_meta_tmdb.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
*** ERROR: ambiguous python shebang in /usr/bin/tvhmeta: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
error: Bad exit status from /var/tmp/rpm-tmp.FMb2Z3 (%install)
```
Changing the shebangs to python3 fixes the whole thing, which is what this patch is about. If you have some python2 systems to still support, feel free to close this, and I can supply a version that uses `sed` in the rpmbuild.  I have a …
> Update Python shebangs to python3 for Fedora

- src/input/mpegts/satip/satip.c
- [SAT>IP Protocol Specification 1.2.2](https://www.satip.info/sites/satip/files/resource/satip_specification_version_1_2_2.pdf): 3.3.2 Server Advertisements: "Please note that in UPnP - header field names are case insensitive and header field values are case sensitive"
- some servers reply with e.g. "Location" or "Server" instead of "LOCATION" or "SERVER"
> SAT>IP client: UPnP header field names are case insensitive

- src/transcoding/codec/codecs/libs/vaapi.c
VAAPI: Buffer factor (buffersize manipulation) now configurable at WebUI.
VAAPI: Added rc_mode (h264/hevc) and tier (hevc), both configurable via WebUI.
VAAPI: Removed B-Frame workaround from the past at HEVC.
VAAPI: Added an option for ignore b-frames because some drivers needs this (AMD).
VAAPI: Also updated VP8 and VP9 encoding.
VAAPI: VP8 and VP9 now also reacts on options for "Buffer factor" and "Ignore B-Frames" and got the "force_key_frames" expression to increase picture quality.
VAAPI: Added destroy option for h264 codec (might have created memory issues)
> Update for VAAPI transcoding

- src/satip/rtsp.c
Originally, the code did not parse 'src' in RTSP-requests for
DVB-C tuners. This patch moves to always parse the parameter,
allowing e.g. Plex and possibly other SAT>IP-clients to work.
Signed-off-by: Nita Vesa <werecatf@outlook.com>
> Always parse 'src' in RTSP-requests

- src/http.c
- src/utils.c
Fix the following build failure with libressl raised since https://github.com/tvheadend/tvheadend/commit/e61acb8ad4a3411f4e7acfd8133d222299f6d47e:
```
utils.c:(.text+0x1614): undefined reference to `EVP_sha512_256'
```
Fixes:
- http://autobuild.buildroot.org/results/cb18f6533806f3729f9718bdcc719384be375b66
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
> fix build with libressl

- src/utils.c
U+0020 SPACE and U+00A0 NO-BREAK SPACE look the same, but they
aren't the same.
> Fix FTBFS in utils.c

- src/http.c
Issue originally reported: https://tvheadend.org/issues/6146
Re-verefied on master: 26713c1e451a74dbcc7aaec8427c0356cc2c546f
> add Access-Control-Allow-Headers content-length

- src/misc/json.c
Building Tvheadend on Raspberry Pi with gcc 12 fails with this error
src/misc/json.c: In function ‘json_parse_string’:
src/misc/json.c:120:31: error: pointer ‘r’ used after ‘free’ [-Werror=use-after-free]
120 |                   *failp = (a - r) + start;
|                            ~~~^~~~
src/misc/json.c:118:19: note: call to ‘free’ here
118 |                   free(r);
|                   ^~~~~~~
This PR appears correct and fixes the gcc error but has not been tested as it is an error path.
> Fix use-after-free

- src/input/mpegts/mpegts_network_dvb.c
When 'change muxes' option for network discovery is enabled, allow network scan to modify muxes rather than duplicate them on minor changes such as FEC.
Looking at the history of changes around this feature, I believe there was a deliberate choice to create a new mux entry every time a transponder is changed via network scan. I can understand the motivation to keep it safe, but this is cumbersome as some satellite operators actively modify PHY parameters for some of their transponders, typically DVB-S2, to adapt to what I believe are either seasonal weather conditions and/or the number of services they want to use at a point in time.
Without this change, I need to manually scrub muxes in the db, and remove duplicates manually on a regular basis. 
The existing code to decide whether a mux …
> Allow network scan to modify muxes

- src/input/mpegts/dvb_support.c
Added support for decoding ATSC's text mode 0x3F
I verified this on a RasPi system with a WinTV-dualHD (Model 1595) receiving South-Korean Terrestrial TV signals. It runs stable and gives the right naming of TV shows and station names.
Thanks to @NormRaden 's fix and implementation of the other text modes, this was very easy to implement. Thanks, mate!
> Added support for ATSC text mode == 0x3F

- src/input/mpegts/dvb_psi.c
I added support for the Logical Channel Numbering for the Romanian cable provider DigiTV (formerly known as RCS&RDS).
For the LCN data they are using private data specifier `0x1a0` and descriptor tag `0x86`
> Add support for LCN for provider DigiTV

- src/input/mpegts/iptv/iptv_auto.c
SiliconDust recently added m3u playlist generation support to the HDHomeRun products.  They use "channel-number" for the channel number, so add support for that value to TVHeadend.  It is used as a fallback only if the previously-supported "tvh-chnum" and "tvg-chno" tags aren't present.  This should be particularly useful for usage with ATSC 3.0 channels, as those aren't supported in the libhdhomerun library that TVHeadend normally uses for HDHomeRun devices.  Without this, the channel number for all channels imported from the HDHomeRun m3u is "0".
> iptv_auto: Add support for m3u "channel-number" tag

- src/epgdb.c
The new epgdb is written to a temporary file and later renamed to override the old epgdb file atomically. If you diverted the epgdb to a different place away from your usual configuration (e.g. for space and/or disk usage reasons like on an OpenWrt router) this leads to overriding the symlink with a real file defeating the point.
By applying realpath on the path first we can resolve any symlink along the path, while not considering it a failure if the epgdb file doesn't exist yet. If on the other hand the path up to the file doesn't exist we default to the old way of just taking the path verbatim and let them be created by hts_settings_makedirs as before.
Note that this relies on the paths being sized PATH_MAX, which as the [manpage](https://manpages.debian.org/unstable/manpages-dev/realpa …
> epgdb: Resolve symlinks before using file location

- Makefile
- src/tcp.c
- src/tcp.h
- src/tvhlog.c
- src/udp.c
- src/upnp.c
Hi,
as #1473 broke compiling with gcc-11 due to a false positive I feel responsible for making it work again, even if is somewhat easy to workaround and semi-temporary (just use a fixed compiler, right? :wink: ).
So what we do here is making tvheadend compile with strict-aliasing rules enabled, which as a by-product apparently doesn't lead gcc-11 down the wrong path. yeaha!
On the downside, I have basically only compile-tested this (on gcc-12 and a bit with gcc-11) as I run tvheadend with `--noacl` and many compiletime options disabled… and while I believe both Makefile changes should be done they might break compiling with older compiler versions or on code which breaks strict aliasing, but isn't detected (and hence potentially wrongly optimized). Disabling strict-aliasing on the entire …
> Avoid breaking strict aliasing in TCP code

- src/input/mpegts/scanfile.c
dtv-scan-tables commit 28414c7 added muxes for South Africa. Add the country to the country codes list.
> Add South Africa to Countries list.

- src/config.c
It make sense to include it always when available
Link: https://tvheadend.org/issues/6223
Signed-off-by: Kacper Michajłow <kasper93@gmail.com>
> config: Enable HbbTV parser by default

- src/htsmsg.h
Fix FTBFS introduced by 7b95ba4cf9113ae8808b3e4a9425010b607dbaca
Link: https://tvheadend.org/issues/6173
Link: https://tvheadend.org/issues/6226
References: 7b95ba4cf9113ae8808b3e4a9425010b607dbaca
Signed-off-by: Cédric Schieli <cschieli@gmail.com>
> Don't confuse GCC with zero-length array

- Makefile
- configure
libavresample is not being used. Builds should not depend on it.
Fixes #6084 and #6219
> remove libavresample from build scripts

- docs/property/duplicate_handling.md
- src/dvr/dvr.h
- src/dvr/dvr_autorec.c
- src/dvr/dvr_config.c
When manually creating an autorec timer using the UI it is possible to specify how duplicate events will be handled. This option is not available if the autorec is created from the UI EPG screen, or using the HTTP API.
This PR adds a default 'duplicate handling' item to the Recording Profile parameters. This default will be applied to all new autorecs which do not specify their own duplicate handling behaviour.
The Kodi HTSP plugin has its own default for duplicate handling so will not be affected.
duplicate_handling.md: Add details of "Record if Unique" option.
> Add autorec duplicate handling default to dvr config.

- src/transcoding/codec/internals.h
- src/transcoding/codec/profile_video_class.c
- provide the ability to specify if scaling should be performed Up and Down, Up (only) or Down (only)
> profile video resize improvements

- src/input/mpegts/linuxdvb/linuxdvb_en50494.c
- src/input/mpegts/linuxdvb/linuxdvb_satconf.c
Currently, the Unicable settings are always cleared when enabling or disabling the corresponding satellite position or its owning adapter. The reason is that the `idnode` with Unicable configuration is always unconditionally deleted during the "set" operation.
This change adds a check for the existing Unicable configuration and preserves the existing `idnode` if its type remains the same.
The same logic is already used when changing the configuration related to LNB, switch and rotor.
> Preserve existing Unicable idnode during the set operation

- src/dvr/dvr_db.c
Some channels add "New: " to the title if this is the first showing, so a title match with repeats will fail.
If we are going on to check CRIDs, ignore any title mismatch.
> Ignore title mismatch if dup checking by CRID

- Makefile.ffmpeg
- src/transcoding/codec/codecs/libs/vaapi.c
- src/webui/static/app/codec.js
- replaced tvherror() with tvhinfo for bitrate report
- converted from bps to kbps
- reduced B frame to max 3 (4 is generating artifacts on my system)
- I had to set also bf otherwise will be set later in profile_video_class() with 3
- when low power is enabled max B frame will be disabled (because codec is not using B frames in low power mode)
- h264_vaapi and hevc_vaapi have also dynamic enable/disable for max B frame
- vp9 super frames can be enabled/disabled from the interface
- clean-up some javascript code
> vaapi update:

- src/epggrab/otamux.c
Currently OTA scan is running for IPTV streams as well. Further details here: https://tvheadend.org/issues/5629
Here's small patch that implements 'does not run epggrab is mux is MM_EPG_DISABLE'.
> Fix for DVB Grabber and IPTV Stream

- src/epggrab/otamux.c
- src/tvheadend.h
on some 32bit systems   time_t  has a size of 64 bit  ( alpine with musl => 1.2, or glibc with D_TIME_BITS 64 option) 
tested on a  armv32 arm sbc and on x86 with qemu emulation
> fix for 64bit time_t on 32bit systems

- Makefile
- configure
- src/intlconv.c
TVHeadend has a hard-dependency on libiconv. Lets make this a little bit more flexible by also allowing gnu-libiconv.
This helps with musl-based systems, such as Alpine Linux.
Contributes to #4940.
> iconv: Allow using GNU libiconv

- src/transcoding/codec.h
- src/transcoding/codec/codec.c
- src/transcoding/codec/internals.h
- src/transcoding/codec/profile.c
- src/transcoding/codec/profile_video_class.c
- src/transcoding/transcode/context.c
- src/transcoding/transcode/internals.h
- src/transcoding/transcode/stream.c
- updated 'AVCodec' to 'const AVCodec'
- "avctx->refcounted_frames = 1;" deprecated (not required with: avcodec_receive_frame())
> updated 'AVCodec' to 'const AVCodec'

- support/tvhmeta
Construct and add an Authorization header to the request, when a username and password are provided to tvhmeta.
This fixes #6260.
> tvhmeta: Fix tvhmeta authentication to the tvheadend API.

- lib/py/tvh/tv_meta_tvdb.py
Typo 'languague' prevents the script from fetching poster art.
Fixes #6262.
> tv_meta_tvdb.py: Fix 'languague' typo.

- Makefile.ffmpeg
- src/input/mpegts/iptv/iptv_libav.c
- src/muxer/muxer_libav.c
- src/transcoding/transcode/video.c
- support/patches/ffmpeg.libx264.diff
- added new config flag: ffmpeg5
- Makefile.ffmpeg added to 5.1.2
- src/muxer/muxer_libav.c: update 'AVOutputFrmat' to 'const AVOutputFrmat'
- src/transcoding/transcode/hwaccels/vaapi.c --> incorporated the struct from libavcodec/vaapi.h (probably not the most optimal option)
- src/transcoding/transcode/video.c: update type for qdata_size
> update to ffmpeg 5.1.2

- src/webui/simpleui.c
To determine if the server is online, we want to be able to 'ping' it with as little configuration and access possibilities as possible. The only available option for this today, is anonymous access.
Let us thus add a new endpoint, that replies with 'PONG' when queried.
This will need anonymous access enabled, but can be restricted to: a) localhost
b) without any access permissions
A simple way to 'test' this, is with busybox's wget and grep.
```
wget -O - -q http://172.17.0.5:9981/ping | grep -q PONG
```
which should return 0 on success, 1 otherwise.
> Add simple 'ping' endpoint

- .github/workflows/build.yml
Follow-up for #1533; I did not realize that the Ubuntu image was a VM, not a container.
@Flole998 dixit
> That's because "fedora-latest" is most likely not a valid image name that GitHub actions can use. There is a list somewhere and you need to choose one of the options from that list, otherwise it will just wait forever until the specified one becomes available (which might never happen).
Could you run this pipeline before merging?
> No need for a Fedora host for fedora images

- src/spawn.c
When close is called with a non-existant file descriptor, it will happily do so. Since we do not even check for the error code, trying to close a non existant/not-open file descriptor does not even cause an error.
This in itself is not a problem at all, however, we try to close every open file descriptor beyond stderr, upto whatever _SC_OPEN_MAX returns.
Some systems may have a very large ulimit set for `_SC_OPEN_MAX` and thus `maxfd` may return something in the millions*. This means that the simple `for() close();` loop now has to iterate a million file descriptors which may not even be open/exist.
Instead, we can use the power of `/proc/self/fd` to list our open file descriptors, and only close open ones.
*It can actually even be a billion, as it is for the root user. While nobody …
> spawn: Do not close every possible file descriptor

- src/config.c
- src/dvr/dvr_config.c
For server configurations, we want to store recordings somewhere sensible.
While here, lets 'abuse' this merge request to fix the following:
The internal print functions already add the newline for us, so adding one manually is not needed.
Further more, a tab got snook in, where spaces where intended.
This fixes commit dbf973307ae3 ("dvr_storage: Use XDG spec directories") which accidentally introduced this.
> config: Store recordings sensibly on servers

- debian/tvheadend.postinst
- debian/tvheadend.postrm
- src/config.c
- src/main.c
This updates the Debian packaging to use the new configuration directories introduced by
https://github.com/tvheadend/tvheadend/pull/1535 and https://github.com/tvheadend/tvheadend/pull/1538.  Instead of being in /home/hts/.hts/tvheadend, the configuration will now be stored in /var/lib/tvheadend by default, which is consistent with how many other "server"-style Debian packages handle their home directories and configuration.
It also fixes the logic in config.c:config_get_dir() to properly support the forking mode of operation.  Since config_get_dir() is executed before forking, the uid will always be 0 at this point. Instead, use the uid of the user to which we will fork if a fork will occur.
> Update Debian packaging to use the new configuration directories

- src/dvr/dvr_config.c
A change was made in commit dbf9773 which replaced getcwd() with get_current_dir_name() (a GNU extension).  This patch reverts that change so that tvheadend can compile on non-GLIBC systems.
> Revert non-portable function to previous code

- src/epggrab/module/eit.c
The EIT grabber was looking for the rating byte at the wrong position.
[https://tvheadend.org/issues/6284](https://tvheadend.org/issues/6284)
ETSI EN 300 468 describes the 'parental_rating_descriptor' value is in the 4th byte of the payload, not the 1st byte.
> Bug Fix: epggrab: OTA EIT Parental Rating

- Makefile
- src/tvheadend.h
In issue #6257 an issue mentioning that time_t isn't properly supported when printing on 32-bit systems, specifically on FreeBSD. However, intel 32-bit systems suffer from a similar fate:
src/rtsp.c:333:30: error: format '%ld' expects argument of type 'long int', but argument 4 has type 'time_t' {aka 'long long int'} [-Werror=format=]
333 |   snprintf(buf, sizeof(buf), "npt=%" PRItime_t "-", position);
|                              ^~~~~~~                ~~~~~~~~
|                                                     |
|                                                     time_t {aka long long int}
In commit 76a6263f1be4 ("fix for 64bit time_t on 32bit systems") was attempted to be fixed by turning it into a PRId64, which was reverted again in commit 9e1eb89be731 ("Revert "fix for 64bit …
> Fix time for 32bit systems again

- src/dvr/dvr.h
- src/dvr/dvr_db.c
- src/htsp_server.c
- src/muxer/muxer_mkv.c
- src/webui/static/app/dvr.js
An 'age_rating' field has been added to the recording objects stored in '{TVH}/dvr/log'.  It is populated from the associated EPG event when a recording is created using the WebUI, HTSP API or JSON API.  It is also populated via HTSP/JSON API if the field is specifically included during the manual creation of the recording object.
This field can be accessed via:
1) the WebUI recording list pages (Upcoming, current, finished, failed, removed);
2) the '/api/dvr/entry/???' JSON API in the new 'ageRating' property;
3) the HTSP API 'dvrEntryAdd' and 'dvrEntryUpdate' methods in the new 'ageRating' property and;
4) saved in the MKV 'LAW_RATING' tag as a number (for now).
The new property name 'ageRating' for the DVR recording API object was selected to be consistent with the existing EPG API …
> Add 'age rating' field to recording metadata - Feature #6287

- configure
It looks like the compile check doesn't work properly on some architectures, which appears to eat or ignore the -Werror flag.
Instead, be more specific in that we state that printf formatting errors are to be triggered on, and treated as an error explicitly, which in the end is exactly what we are after.
> Use explicitly on format warnings for Time test

- src/epggrab/otamux.c
As %li isn't supported equally, we must ensure we always use PRItime_t.
> otamux: Make sure we use PRItime_t

- support/mkbundle
Fixes build error with python-3.12:
Traceback (most recent call last):
File "support/mkbundle", line 48, in <module>
import distutils.spawn
ModuleNotFoundError: No module named 'distutils'
> support/mkbundle: switch from distutils to setuptools

- src/htsstr.c
There seemed to be a flaw in the splitting logic when it comes to quotes, e.g.: --output="filename" should be one argument, but htsstr_argsplit treated it as ['--output=', '"filename"] which I think is wrong.
I don't have the setup to test this code so I would appreciate it if someone else does.
> Fix htsstr_argsplit

- src/api/api_service.c
- src/dvr/dvr_vfsmgr.c
- src/idnode.c
- src/input/mpegts/mpegts_input.c
- src/notify.c
- src/notify.h
- src/subscriptions.c
- src/webui/comet.c
- src/webui/webui.h
All the way back in 54e63e3f9af8fdc0d23f61f3cda7fa7b246c1732, there was a fix to stop non-admin users from receiving log messages with potentially-sensitive data.  However, this stopped non-admin webui users from receiving almost any updates over the websocket interface, which causes a bug where such users don't see newly- created DVR entries, etc. until refreshing the page.  This patch allows for more granular control over what non-admin users receive.  Specifically, messages originating from subscriptions.c, mpegts_input.c, and api_service.c, along with all log messages, are still only sent to admins because they may contain sensitive data and/or they are only relevant to administrative parts of the UI. Other messages, such as idnode, DVR, and EPG-related messages, are once again sent …
> Fix non-admin users not receiving any updates in web UI

- support/tvhmeta
Set default value "True" on 'okay' in fetch_and_persist_artwork function call, so that calls can succeed when no error condition is met.
Fixes #6310.
> 6310 Set 'okay' default to True

- src/input/mpegts/iptv/iptv_auto.c
Like strtok(), http_tokenize() modifies its input string. Since those strings are needed later to populate the UI, we should use copies.
Also free ignore_args to avoid a memory leak.
> Correct handling of Remove and Ignore settings, fixes 6309.

- .github/workflows/build-cloudsmith.yml
- .github/workflows/build.yml
- Autobuild/lunar-aarch64.sh
- Autobuild/lunar-armv7l.sh
- Autobuild/lunar-x86_64.sh
- Autobuild/lunar.sh
- Autobuild/mantic-aarch64.sh
- Autobuild/mantic-armv7l.sh
- Autobuild/mantic-x86_64.sh
- Autobuild/mantic.sh
blind changes, can't test locally
- remove EOL distros besides old TLS
- reorder releases by date
- add new build targets Ubuntu 23.04, 23.10 and Debian Trixie
- left out i386 for new targets, Ubuntu already dropped 32bit
not sure if Debian 13 i386 is needed ?
> update ci builds

- .github/workflows/build-cloudsmith.yml
This prevents changes to `.github` and subdirs like `.github/workflows` from triggering a cloudsmith repo build.
> ci: don't trigger cloudsmith on .github changes

- .github/workflows/build.yml
- .github/workflows/test-compile.yml
This PR adds concurrency to workflows so force pushes to a pull-request automatically cancel any active/pending runs that resulted from the original submission.
> ci: add concurrency to the main CI workflows

- .github/workflows/coverity.yml
This adds a weekly scheduled scan at 0700 on Mondays to coverity config.
> ci: schedule weekly coverity scans

- src/webui/extjs.c
Simply update the WebUI copyright message so it's current, and correct Andreas' surname since it changed some time ago.
> Update copyright year and correct current surname

- configure
- src/config.c
- src/config.h
- src/htsmsg.c
- src/htsmsg.h
- src/htsmsg_json.h
- src/webui/webui.c
Closes https://tvheadend.org/issues/4461
This is an attempt to cleanup the previously rejected #1348:
- I removed all code related to the authentication bypass 
- harmonized the comment format.
- Successfully tested by using IP based authentication and Plex
I kept the previous commit to highlight the new changes, but happy to squash if that's preferred.
> hdhomerun: Add HDHomeRun server emulation support for LiveTV only

- LICENSE.md
- Makefile.static
- README.md
- lib/api/python/README.md
- src/string_list.c
- src/string_list.h
- src/webui/static/app/epgevent.js
- support/eitscrape_test.py
- support/lib.sh
- support/template/header.c
- support/template/header.h
- support/template/header.py
- support/template/header.sh
Markdown docs and i18n files have been omitted as these files are likely to be replaced.
> Replace "Tvheadend Foundation CIC" with "Tvheadend Project"

- support/cloudsmith.sh
There's a missing | separator between `raspiosjessie` and `raspiosstretch` but a wildcard is easier.
> ci: fix raspios detection in cloudsmith.sh

- support/cloudsmith.sh
Xenial (and possibly others) builds have been failing for a while, because the Python 3.5 on it isn't compatible with the latest Pip.
This PR changes that it only upgrades Pip if Python is 3.6 or higher, otherwise rely on the system Pip.
> ci: fix Cloudsmith upload for distros with Python 3.5

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_proposal.yml
This adds yaml templates for bug reports and developer feature proposals, and general links to the forum for user feature ideas and support requests. NB: version info in the bug template looks towards the future (but not that far hopefully).
> issues: add template files in preparation for GitHub issues

- intl/docs/tvheadend.doc.lt.po
We have template discrepancies between `tvheadend/intl` and the sub-directories contain the .po strings. Language strings/templates for Lithuanian (lt) are in `tvheadend/intl` and `tvheadend/intl/js`, but are missing from `tvheadend/intl/docs`.
The language exists on Transifex, so I'm assuming that it's an import error (i.e. no target into which to import the translated strings). There appears to be nothing in the code or Makefile that creates these files otherwise.
This forces the creation of a template by simply copying the master `tvheadend/intl/docs/tvheadend.doc.pot` to `tvheadend/intl/docs/tvheadend.doc.lt.po`.
> Add missing Lithuanian string template

- src/main.c
- src/tvh_thread.c
- src/tvh_thread.h
The behavior of signal() is not consistent or defined when using it to set signal handlers (see "Portability" in
https://man7.org/linux/man-pages/man2/signal.2.html).  Previously we got away with this, but starting with GCC 14, using signal() apparently causes certain syscalls to be restarted after the signal is caught.  One of these is the read() currently on line 63 of fsmonitor.c.  The result is that read() doesn't return when the fsmonitor thread receives a signal, resulting in the thread never shutting down, resulting in TVHeadend hanging on any attempt to terminate it.
Instead, use sigaction(), which has defined behavior when setting signal handlers.  Since invoking sigaction() requires several lines, a helper was added to tvh_thread.c to avoid code duplication.
> Use sigaction() instead of signal()

- src/main.c
When using the `--fork` flag, and no user or config arguments are
supplied, the configuration folder will end up with whatever the default
`daemon` user has set, which is often `/sbin` set as the homedir.
This is weird, but not 'wrong' per say. Lets warn the user that forking
can have an unexpected side effect.
Contributes to https://tvheadend.org/issues/6296
> Warn missing config

- debian/tvheadend.postinst
- debian/tvheadend.postrm
Detect if the HTS user's home directory starts with "/home/", which
indicates the legacy configuration directory is in use, and use the
correct paths for the "recordings" directory and "superuser" file.
This prevents a useless files/directories from being created and
ensures that "dpkg-reconfigure tvheadend" still updates the
superuser credentials correctly.
Also, clean up several issues in the postinst and postrm scrips in a separate commit for ease of code review.
> Fix handling of legacy configuration directories in debian/postinst

- docs/markdown/cmdline_options.md
- man/tvheadend.1
- src/main.c
The satip_boot function was added to config_boot in commit 442a871839bb ("satip server: fixed the RTP TCP size initialization, fixes #4517"), which doesn't tell us at all why it is there.
Whats worse, the nosatip flag seems to be ignored and the satip server still gets loaded.
Move things around a little so we can put them together under the nosatip flag to honor the intend better.
> satip server: Rename nosatip to nosatipcli CLI flag

- docs/property/change_parameters.md
The Change Parameters flag on the Access Entries screen for a user determines whether that user's settings will override any previously-set parameters (for example from a wildcard user) - it does not affect the ability of subsequent users to override settings in turn. The exception is the 'Rights' settings where all matched users with the Change flag set are ORed together.
This is a copy of PR #1335 which cannot be rebased onto current master.
> Correct description of Change Parameters flag

- src/config.c
Since https://github.com/tvheadend/tvheadend/pull/1540, enabled by https://github.com/tvheadend/tvheadend/pull/1535 and https://github.com/tvheadend/tvheadend/pull/1538, we have been storing the recordings in a subdirectory of the configuration directory by default.  Because of this, the recordings are getting stored in the configuration backup.  This causes the backups to take forever and fill the disk (see
https://github.com/tvheadend/tvheadend/issues/1625).  Instead, exclude the "recordings" directory from the backup to prevent this.
Fixes: #1625
> Add "recordings" to the backup exclude list

- src/dvr/dvr_db.c
`strerror` takes the `errno` directly as its argument, negating it will result in an "Unknown error".
> dvr: Fix incorrect usage of `strerror`

- src/transcoding/transcode/log.h
> transcoding: access the codec name only when codec pointer is valid

- .dockerignore
- .github/workflows/container-build.yaml
- Containerfile
- Containerfile.alpine
- Containerfile.debian
- Dockerfile
- README.Docker.md
- README.md
- configure
- support/container-entrypoint.sh
Containers have become quite popular, especial when running 'server software'. TVHeadend shouldn't miss out here.
This MR creates a container and uses github actions to build and push these to the github container registry (ghcr.io) which is 'included' in each github repo.
Running tvheadend becomes then as simple as `docker run --rm --interactive --tty --publish 9981-9982:9981-9982/tcp ghcr.io/tvheadend/tvheadend:latest --help`.
It is not as advanced as linuxserver/tvheadend as they add additional programs, not yet? packaged or which should really be handled differently (separate containers/volumes).
Once a few relases have been tagged, and everything works well, extending the action with a secondary login to also push to docker hub for example, is easily possible.
Enjoy!
This MR now …
> container: Offer TVHeadend container

- .github/workflows/container-build.yaml
We have to make sure we clone the whole repo, so that `git describe` works as expected. Without it, we get version 0.0.0, not what we want.
> CI: Ensure we clone the whole repo

- intl/docs/tvheadend.doc.pot
- intl/js/tvheadend.js.pot
- intl/tvheadend.pot
This PR updates the master English language translation templates against source code for the first time in almost seven years. As such the diff is large and the PR must not be merged until we see positive runtime reports.
The master templates are regenerated using `make intl` which fails due to broken dependencies on `src/version.c` and `src/docs_inc.c` not existing so a full build is required (which creates them) before `intl` can succeed. This needs to be resolved in a future PR before we can consider automating template udpates.
> intl: update translation templates from code

- src/bouquet.c
In a mixed network environment (such as DVB-T and DVB-S) it is common
to receive many of the same channels. However, with "auto map to
channels" on a bouquet, you could not merge the channels across the
network bouquets.
Now we create a separate "Tvheadend Network" in the bouquets and allow
"auto map to channels" on it. Any other bouquets that are enabled but
do _not_ have "auto map to channels" enabled will be added to the
enabled "Tvheadend Network".
So, if "DVB-T Network" and "DVB-S Network" in the bouquet tab are both
enabled _and_ their tickbox for "auto map to channels" is deselected,
then their services will be added to the "Tvheadend Network". That can
then be enabled with "merge channels" to produce the merged channels.
We call it "Tvheadend Network" instead of "Tvheaded Virtual …
> bouquet: Allow merging of services across network bouquet, fixes #5617

- src/http.h
Single bit signed integers contain a single sign-byte and zero value bytes according to the C99 standard. This is not inteded here.
> Replace single-bit signed integers with unsigned integers

- src/config.c
- src/dvr/dvr_rec.c
- src/dvr/dvr_vfsmgr.c
Discussed in Issue: https://github.com/tvheadend/tvheadend/issues/1638
Log some error numbers and error messages for file system errors in the DVR module.
Modified error messages:
```
2024-02-19 13:11:44.594 [  ERROR] dvr: '/home/tvhtest/text.txt' is not a directory. (ERRNO: 2)
2024-02-19 13:12:27.654 [  ERROR] dvr: Directory '/home/tvhtest/not_found' not accessible.  ERRNO: 2, 'No such file or directory'
2024-02-19 13:30:41.169 [  ERROR] dvr: Directory '/home/dmc/recordings' not accessible.  ERRNO: 13, 'Permission denied'
2024-02-19 13:39:03.183 [  ERROR] dvr: unable to stat file '/home/dmc/Jazz Lunch.ts' (ERRNO: '13')
```
This may help users more easily identify the cause of their error.
Fixes: #1638
> Add some ERRNOs for DVR

- src/webui/static/app/dvr.js
Allows the 'Series Link' field to be visible in the AutoRec WebUI.
https://tvheadend.org/d/8513-improvements-to-autorec-series-tracking-webui-indications
> Show SeriesLink for AutoRecs

- .github/workflows/build-cloudsmith.yml
Per discussion with Flole, the username of the account uploading to cloudsmith does not need to be public. Switching it to a secret will mask it in CI output.
This will require a change to the repository secrets.
> ci: change CLOUDSMITH_OWNER from a var to a secret

- docs/wizard/channels.md
- docs/wizard/channels2.md
Update the 'donate' link at the end of the setup wizard to point to OpenCollective.
Include logo with link.
> Update OpenCollective donate link on Wizard

- support/cloudsmith.sh
- colors `echo` output for visibility
- exits with `1` if cloudflare API does not return success
- hides cloudsmith response unless there is an error
> ci: added more info logging to cloudsmith.sh

- src/dvr/dvr.h
- src/dvr/dvr_autorec.c
- src/dvr/dvr_config.c
- src/dvr/dvr_db.c
This PR merges #1330 with already-committed #1488. It adds an extra option "Use DVR Configuration" to the autorec edit screen; when selected (the default) the setting from the DVR Profile is used. Any later change to the DVR profile setting is applied to existing autorecs which do not have their own setting.
> Improve autorec duplicate handling

- src/webui/static/app/tvheadend.js
Commit 2ca8a19 removed the `if (/(\%[yY]+)/.test(format))` check before the `RegExp.$1` usage when replacing the year in custom date formats, meaning `RegExp.$1` no longer pointed to the matched year format code.
This PR fixes this by removing `RegExp.$1` usage, using a function instead to make the code clearer. I've also moved the year handling into the for loop where most other formatting is handled, for clarity.
> webui: Fix year being replaced incorrectly when using custom date format

- src/api/api_config.c
- src/bitops.h
- src/tvhlog.c
Add the ability to extract the available subsystems and their descriptions via the JSON API.
https://tvheadend.org/d/8597-extracting-tvh-subsystems-via-the-json-api
Sample:
```
{
"id": 12,
"subsystem": "fsmonitor",
"description": "Filesystem monitor",
"trace": false,
"debug": false
},
```
**id** - The internal ENUM for this subsystem.
**subsystem** - The name of the subsystem.
**description** - The locale-aware description of the subsystem.
**trace** - True if this subsystem is currently being traced.
**debug** - True if this subsystem is currently being debugged.
> Add subsystems to JSON API.

- configure
Currently, when the value of an option passed to the configure script as argument contains an equal sign `=`, the part of the string up to the second equal sign is used as option. This commit changes how the string is split, so that always only the part up to the first equal sign is interpreted as option.
`${var%=*}` removes everything from the last equal sign, `${var%%=*}` removes everything from the first equal sign.
This allows to pass `CFLAGS`, which usually contain equal signs, like `--cflags="-march=armv6 -mfloat-abi=hard -mfpu=vfp"`.
For reference: https://github.com/tvheadend/tvheadend/issues/1665
> configure: fix parsing args if values contain "="

- src/satip/rtsp.c
Instead or erroring, ignore additional parameters, as required by the specs in  3.5.11 where it says "Unknown attributes shall be ignored by the server"
> satip: Ignore additional parameters

- debian/tvheadend.postinst
aba5e60792177d6a2a867445559f4806973b3258 was causing the username and password to get printed to the console instead of being put in the correct file.  Also, use the modern $() syntax instead of `` and quote all variable assignments.
> Fix echo target for superuser file in Debian postinst

- Containerfile.alpine
The USB group has been removed from upstream alpine in commit bb00d0e4f345 ("main/alpine-baselayout: remove mem and usb group") which was a fixup on commit
f16d0754d601 ("main/alpine-baselayout: remove unused/moved users and groups")
Lets remove it here as well as we cannot join the group any longer.
Besides, device access is probably better managed with host specific udev rules.
> Docker/Alpine: Remove USB group

- src/input/mpegts/tvhdhomerun/tvhdhomerun.c
This commit adds support for ISDB in the type check of the tvhdhomerun_device_create function in tvhdhomerun.c. This allows the function to handle ISDB type devices, which previously would have been changed to a DVB device on startup every time despite overrides.
> tvhdhomerun: Add ISDB to type check in tvhdhomerun_device_create

- src/dvr/dvr_db.c
Previously if you had a directory set on a recording and this recording needed to be rerecorded, the directory was not kept in the new entry.
> dvr: Added missing directory to rerecord-entry

- src/config.c
Clarify that the value of "CORS origin" should be a URL (i.e. prefixed with http:// or https://), and not "bare" domains/IP addresses, as they currently silently fail to save.
Fixes (partially) #1700.
> Configuration: improve CORS origin help/hover message

- src/input/mpegts/linuxdvb/linuxdvb_frontend.c
- src/input/mpegts/linuxdvb/linuxdvb_private.h
When using Astrometa to tune to DVB-T2 muxes in Poland, the scans are reported as complete but the found services have zero elementary services due to the scan period being too short in order to fetch PMTs.
This change allows overriding the default grace period of 5 seconds with a custom value. I successfully scanned all services with this setting changed to 15 for this particular adapter/mux combination.
> Allow setting a custom grace period for LinuxDVB adapters

- src/epggrab/module/xmltv.c
**Description**
See Issue: https://github.com/tvheadend/tvheadend/issues/1709
When processing XMLTV EPG data and rating labels are enabled, a missing 'system' attribute in the 'rating' tag results in a crash.
```
<rating system="DEMO">
<value>TV-PG</value>
</rating>
```
**Resolution:**
If a rating tag is encountered without a 'system' attribute, the literal 'NONE' will be used instead.
> XMLTV: Rating Labels: Use 'NONE' when 'system' attribute is missing

- src/dvr/dvr_db.c
de->de_directory may be null. htsmsg_add_str passes str unchecked to underlying strlen function. __strlen_avx2 will segfault if str is null.
htsmsg_add_str2 checks the value of args before passing them to htsmsg_add_str, which should prevent this.
Fixes #1712
> dvr: Use safer htsmsg_add_str2 when copying de->de_directory

- src/epggrab/module/xmltv.c
- src/ratinglabels.c
Address issue [#1717](https://github.com/tvheadend/tvheadend/issues/1717).
Reverse PR [#1710](https://github.com/tvheadend/tvheadend/pull/1710).
Remove replacement values and allow 'authority' and 'country' to be null.
Allow XMLTV to be matched using only labels of the 'system' is not supplied.
Use null-safe htsmsg function when creating rating label objects.
> [Rating Labels] Revise null value handling.

- src/webui/static/tv.js
The `fullscreen` function in `tv.js` checks for `webkitRequestFullScreen`, but after confirming that it is available, it ends up calling `webkitEnterFullscreen` which does not exist.
This commit changes the fullscreen method detection to something I feel is more straightforward, keeps backwards compatibility (as `webkitEnterFullscreen` is still checked for existence and will be called if possible), and fixes the linked issue.
Fixes #1729 .
> Rework fullscreen request method detection

- src/input/mpegts/linuxdvb/linuxdvb_satconf.c
First of all: thanks for TVH. Great software!
This PR extends the description for "lnb poweroff when idle" to make it clear that lnb_poweroff also requires "power save" setting.
Background: I noticed my SAT multiswitch never going into standby mode thus using >10Watt of unnecessary power 24/7. I traced it down to one of my adapters not turning off LNB power. Took me some time of triaging to figure out that the "LNB Poweroff when idle" setting only works, if you also set the "power save" setting.  
In my opinion it is quite bad UI design to have a hidden dependency on some other option. I extended the description to make it clearer that there is a dependency. A better solution would probaby be to remove this dependency and have it always work, no matter if "power save" is set or not.
> Update linuxdvb_satconf.c  description for lnb_poweroff - requires power save

- src/transcoding/codec/profile_audio_class.c
There are few issues:
1. first entry in combo should be AUTO (with value 0) - in original code was set to 1 (and overwritten later)
2. l->nb_channel is not the best way to cycle though layouts available. At the end I think is accessing some region outside of the struct (because I see is lopped also after 7.1). The way I knew how to fix was to add the filter (l->nb_channels < 32). Maybe changing the while to for will be a better option.
3. av_channel_layout() is returning the length of the string ... we should use l_buf only when retuned value > 0 ... when is < 0 l_buf was not updated.
> fix bug in AAC channel layout configuration tab

- src/transcoding/codec/codecs/libs/vaapi.c
Older versions of GCC don't like declaring a variable in the middle of a switch/case and will fail with "error: a label can only be part of a statement and a declaration is not a statement".
> Fix FTBFS introduced by 76d8fc8bc5455322558c764c84755ebbba254ad5

- src/htsp_server.c
Sorry, typo in https://github.com/tvheadend/tvheadend/commit/fc5a1672e083155193f3daf697748780f0d02aa9
> Fix mapping HTSP field 'broadcastType' to internal field. Must be 'btype".

- src/dvr/dvr.h
- src/dvr/dvr_db.c
- src/htsp_server.c
- src/ratinglabels.c
1) UUID
For existing message types that use a u32 ID field, for example `channelAdd`, `tagAdd` and `dvrEntryAdd`, add full UUID as a 32 character string for interoperability with objects returned via the HTSP JSON proxy APIs.
2) Rating Labels
a) Add the country and authority values to HTSP messages carrying parental rating labels.
b) Add the saved country and authority values to completed recordings.
This is so that clients (like Kodi) can use the rating properties held by TVH to interpret their own rating labels if required.
3) HTSP version increased to 41.
> HTSP Updates for UUID and Rating Labels

- src/profile.c
- src/profile.h
- src/webui/webui.c
This allows overriding the hardcoded grace period of 20 seconds.
It should address the problems described in [1][2].
In addition, timeout code has been slightly refactored for readability and more debug logging.
[1] https://tvheadend.org/d/8330-increase-timeout-when-tuning-iptv-mux/2
[2] https://tvheadend.org/d/8158-several-problems-questions-about-using-tvheadend-starting-with-not-waiting-long-enoough-for-stream-to-begin
> Add start timeout to streaming profile

- src/transcoding/transcode/helpers.c
src/transcoding/transcode/helpers.c  : pktbuf_len(self->input_gh)) will be 0 (empty) so will return error -11 (AVERROR(EAGAIN) for audio streams.
> Fix - Audio transcoding not working #1663

- Autobuild/bionic-aarch64.sh
- Autobuild/buster-aarch64.sh
- Autobuild/focal-aarch64.sh
- Autobuild/raspiosbookworm-armv7l.sh
- Autobuild/stretch-aarch64.sh
- Autobuild/xenial-aarch64.sh
Please have a look before merging, I'm not sure if this way of excluding is how it should be made. I'd prefer avoiding the redundancy, but it might be necessary because there's no "common denominator" for the combinations.
> chore(build): remove x265 from unsupported platforms

- src/webui/static/lovcombo/lovcombo-all.js
Firefox 134 added the RegExp.escape() method
(https://tc39.es/proposal-regex-escaping/#sec-regexp.escape) with a standards-compliant implementation that throws TypeError if any value other than a String is passed in.  This differs from the existing polyfill that simply returns the argument unmodified if it isn't a String.  In TVHeadend, the day-of-the-week selector (as used in the Autorec and Timer configuration) uses Integers as keys for options, causing an Integer to get passed to RegExp.escape() on line 300 of lovcombo-all.js.  Because of the non-standards- compliant permissive behavior of the polyfill, this previously didn't cause an issue.  However, with Firefox 134 (and an upcoming version of Safari), the added standards-compliant method causes a TypeError to be thrown on every …
> lovcombo-all.js: Fix autorec create/edit TypeError with Firefox 134

- src/httpc.c
The TLS Client Hello message is larger in OpenSSL 3.5 and will not fit in the previous hc_io_size of 1024 bytes.  This causes the TLS Client Hello message to be truncated, resulting in HTTPS requests stalling and eventually timing out.  To fix this, increase hc_io_size to 2048 bytes.
> httpc.c: Fix HTTPS with OpenSSL 3.5

- docs/property/page_size.md
- src/access.c
- src/access.h
- src/config.c
- src/config.h
- src/webui/comet.c
- src/webui/static/app/config.js
- src/webui/static/app/idnode.js
- src/webui/static/app/tvheadend.js
Add a global default setting for 'Items per page' for lists in the UI.
The value is set to 50 (the current UI default) unless changed by the user.  Once changed, every list page will be limited to the value specified.
Each list can still be individually set for the current session but will be reset to the new default for each new session.
> Global setting for 'Items per page'

- src/dvr/dvr_db.c
Bug fix for issue: https://github.com/tvheadend/tvheadend/issues/1809
Code was testing for `de->de_subtitle` instead of `de->de_summary` when updating `de->de_summary`.
> Fix crash when updating 'disp_summary'

- src/wizard.c
GCC 15.1 introduces stricter checks around `snprintf`-like functions under `-Wformat-truncation`, even when the format string itself is under developer control. This triggers a false positive in `hello_changed()` when building with `-Werror=format-truncation`:
error: ‘__builtin___snprintf_chk’ output may be truncated before the
last format character [-Werror=format-truncation=]
note: output between 1 and 33 bytes into a destination of size 32
This warning is triggered due to a theoretical edge case in `tvh_strlcatf()` where combining strings like `"en,fr,de"` could approach the buffer limit of 32 bytes. While truncation is unlikely in practice, the warning is still emitted aggressively by the new FORTIFY logic.
Increase the buffer from 32 to 64 bytes to silence the warning and ensure …
> Fix GCC 15+ format-truncation compile error by enlarging EPG language buffer

- src/webui/static/app/dvr.js
- src/webui/static/app/idnode.js
In the DVR 'Information' window, show the full file name and path for recordings where the user 'interface level' or the 'UI grid view level' is higher than 'Basic'.
> Show recording file name on DVR info page

- src/transcoding/codec/codecs/aac.c
- src/transcoding/codec/codecs/libs/libx26x.c
- src/transcoding/codec/codecs/libs/nvenc.c
- src/transcoding/codec/codecs/libs/vaapi.c
- src/transcoding/codec/internals.h
- src/transcoding/codec/profile_audio_class.c
- src/transcoding/codec/profile_class.c
- src/transcoding/transcode/audio.c
- src/transcoding/transcode/context.c
- src/transcoding/transcode/hwaccels/vaapi.c
- src/transcoding/transcode/internals.h
- src/transcoding/transcode/video.c
- src/webui/static/app/codec.js
remove audio abuffersink options starting ffmpeg7 as recommended in ffmpeg-7.0/doc/examples/filter_audio.c line 177 --> "/* This filter takes no options. */"
Fixes: #1764
> update audio abuffersink from deprecated channel_layouts to ch_layouts

- src/epggrab/module/eit.c
- src/input/mpegts.h
- src/input/mpegts/mpegts_service.c
Provide a number of EPG Sub-title processing options on an individual service basis for EPG data received via the DVB OTA EPG grabber.
1) If the Title and Sub-title are identical, save an empty Sub-title.
2) When the EIT: EPG Grabber ‘Short EIT description’ is set to ‘Subtitle’:
a) If the Description is empty, save the Sub-title as the Description and save an empty Sub-total.  Do nothing if the Description is not empty.
b) If the Description is not empty, append the Sub-title to the Description and save an empty Sub-total.  If the Description is empty, proceed as per option 2a.
c) If the Description is not empty, prepend the Sub-title to the Description and save an empty Sub-total.  If the Description is empty, proceed as per option 2a.
Forum Discussion: …
> Add Sub-Title Processing Options for DVB OTA EPG

- src/transcoding/codec/profile_audio_class.c
My understanding is that htsmsg_create_map() is allocating memory and ADD_ENTRY() is consuming that.
We should always have pairs of htsmsg_create_map() <--> ADD_ENTRY()
If we check the code (before update) - with GREEN is when LIBAVCODEC <= 59 and with RED when LIBAVCODEC > 59:
GREEN has clear pairs: 1 <--> 2 and 3 <--> 4
RED has 1 <--> 2 , but 3 <--> 4 is only when 5 == TRUE 
When 5 == FALSE memory is allocated but is not consumed.
The fix proposal is:
This will always guarantee (no matter what 5 will be) we have pairs:  1 <--> 2 and 3 <--> 4
Fixes: #1749
> fix memory leak

- src/transcoding/transcode/video.c
Fixes coverity scan issues: 462150
practically is impossible to reach that code ... and default will generate the same outcome.
> fix dead error condition

- src/transcoding/transcode/context.c
- src/transcoding/transcode/stream.c
- src/transcoding/transcode/transcoder.c
This pull request introduces two related improvements to Tvheadend's transcoding subsystem, specifically targeting robustness and diagnostics when using hardware-accelerated decoding (e.g., VAAPI).
The first change improves fault tolerance by treating certain hardware decoder errors (EIO, EINVAL) as recoverable. These errors are observed in real-world conditions (e.g., malformed streams or signal glitches) and are tolerated by FFmpeg without aborting the transcoding session. Aligning Tvheadend’s behavior with FFmpeg avoids unnecessary stream teardown, reducing disruption for both live playback and recordings.
The second change enhances visibility into transcoding failures by logging detailed information when packet processing fails. This includes the packet PTS, the underlying error code, …
> Improve handling and diagnostics of transcoding errors

- src/htsp_server.c
This commit adds the is_new flag to the EPG event data sent to HTSP clients. By including this property, clients such as Kodi (with the pvr.hts addon) can now detect whether a broadcast is marked as new and set corresponding flags (e.g. EPG_TAG_FLAG_IS_NEW in Kodi).
This enhances the metadata available to clients and supports improved EPG event handling and display.
A corresponding pull request will also be submitted to the pvr.hts project to make use of this flag when obtaining EPG event guide data from Tvheadend.
> Expose is_new flag in HTSP EPG event data

- src/htsp_server.c
When scheduling a recording via HTSP (Kodi client), the '(Default profile)' is used instead of the user's nominated DVR Configuration profile.  However, when the same operation with the same user is performed via the WebUI, the correct profile was used.
Align the HTSP DVR Configuration profile selection process with the process used in the equivalent JSON API function [dvr_config_find_by_list()].
https://github.com/tvheadend/tvheadend/blob/42ed6affc42ef06e427fb8b1465532a4489e182c/src/api/api_dvr.c#L145C1-L147C64
Tested by scheduling a recording from Kodi with the same user, with and without a nominated DVR profile.  Please note, the HTSP connection retains its previous settings until reauthenticated.
Fixes: #1855
Supersedes: #1443
> User's DVR Configuration profile not used when scheduling recordings via HTSP

- src/dvr/dvr.h
- src/dvr/dvr_config.c
- src/dvr/dvr_cutpoints.c
- src/dvr/dvr_db.c
Once a recording finishes, create an ‘sm’ file containing Scene Marker 'cut points' based on the EPG scheduled start/stop times and the actual recording start/stop times.  This will allow for easier navigation when skipping pre-padding to find the start of the recorded programme.
It should look something like this:
```
|-Warm-Up-|-Pre-Pad-|------EPG-Event------|--Post-Pad--|
|----------------Service-Subscription------------------|
|--------------Recording---------------------|
^                     ^
Scene Marker A        Scene Marker B
```
These ‘sm’ files are in ‘edl’ format and will be deleted by TVH when the main recording file is deleted.  Even though the file is in edl format, the use of a separate ‘sm’ file, dedicated to scene markers, was selected to enable interoperability with …
> Add Scene Markers to recordings at scheduled EPG event start/stop times

- docs/property/autorec_directory.md
- docs/property/pathname.md
- docs/property/postprocessor.md
- docs/property/postremove.md
- docs/property/preprocessor.md
- src/dvr/dvr_autorec.c
- src/dvr/dvr_rec.c
Create 2 new file name format substitution strings:
`$A` - Event season number
`$B` - Event episode number
Both strings can include an optional zero-padding indicator as follows:
`$2A` will zero-pad to 2 positions, for example, `04`.
`$3B` will zero-pad to 3 positions, for example, `004`.
Valid padding values are 1-9.
If the season number or episode number is 0, then the localised value ‘Unknown’ will be used in place of zero.
With sufficiently accurate EPG data, the formatting string `$t/Season $A/$2B-$u$n.$x` would produce a recording named `/path/to/recordings/{Programme Title}/Season {Season Num}/{Episode Num}-{Episode Name}.ts`.
For example: `/path/to/recordings/Bones/Season 2/06-The Girl in Suite 2103.ts`
When a directory is added to an AutoRec or a Timer begining with ‘$$’, these …
> Add Season number and Episode number to file name formatting strings.

- src/transcoding/codec.h
- src/transcoding/codec/internals.h
- src/transcoding/transcode/video.c
fixes: https://github.com/tvheadend/tvheadend/issues/1818
also fixes a logical define bug: filter_denoise and filter_sharpness should be transferred for all HW accels (not only for VAAPI)
> move filter_hw_denoise and filter_hw_sharpness to tvh_codec_profile_video

- src/input/mpegts/linuxdvb/linuxdvb_adapter.c
This fixes 2 issues with my TBS 5520SE and TBS 5930 USB devices. 
Issue 1: no adapters present in tvh after a system reboot. Tvh required a delayed start (wait for frontend init).
Issue 2: no adapters present in tvh after physically disconnecting/reconnecting the adapter. Tvh required a restart.
> linuxdvb_adapter: increase MAX_DEV_OPEN_ATTEMPTS to 50

- src/transcoding/codec/codecs/libs/vaapi.c
- src/transcoding/codec/internals.h
- src/transcoding/codec/profile_video_class.c
- src/transcoding/transcode/hwaccels/vaapi.c
- src/webui/static/app/codec.js
Move 'deinterlace_vaapi_mode' from the VAAPI codec profile to the generic Main Video Codec Profile, allowing this setting to be applied when using VAAPI hardware deinterlacing with software-based transcode profiles such as libx264.
This fixes a bug where 'deinterlace_vaapi_mode' was left uninitialized for non-VAAPI codec profiles, resulting in invalid filter strings like 'deinterlace_vaapi=mode=21867:rate=2:auto=0' and filter graph setup failures.
The patch also:
- Adds validation for the mode value (range 0–4)
- Dynamically enables/disables the VAAPI mode field in the WebUI based on encoder and decoder settings
- Consolidates enum and mode list generation logic under 'profile_video_class.c'
This ensures that VAAPI deinterlacing can be correctly configured and used across hybrid transcode …
> transcode: fix VAAPI deinterlace mode handling for software profiles

- src/input/mpegts/dvb.h
- src/input/mpegts/dvb_psi_pmt.c
A few of my channels are incorrectly showing up with AC-4 audio streams on Tvheadend's "Service details" screen. These tracks really are AC-3.
I believe that is a bug introduced in #1479, which originally added AC-4 support. This code looks for a DVB descriptor with _tag value_ `0x7f`, but according to [ETSI EN 300 468](https://www.etsi.org/deliver/etsi_en/300400_300499/300468/01.18.01_60/en_300468v011801p.pdf), that is not the _AC-4 descriptor_ but the _extension descriptor_. Tvheadend's `DVB_DESC_AC4` should thus be renamed to `DVB_DESC_EXTENSION`. Only if the extension descriptor's _extension tag value_ is `0x15` do we have an AC-4 descriptor.
Due to lack of an actual AC-4 broadcast, I cannot test my patch for correctness, but at least it stops marking streams with extension …
> dvb_psi_pmt: Don't recognize all extension descriptors as AC-4 audio

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/workflows/enforce-issue-template.yml
The current GitHub issue template claims v4.3 is `development` but we have declared it to be `stable` and v4.4 does not exist, so reflect that in the releases drop-list. Also update the distro drop-list with some newer items.
> issues: misc. template updates

- src/transcoding/transcode/video.c
The encoder configuration debug message previously included embedded `\n` to print multiple lines. Following maintainer guidance discussed on Slack, update the log to output everything on a single line instead.
This keeps the configuration details (framerate, time base, frame duration, GOP size, sample aspect ratio) visible in one log entry, making it easier to grep and parse while staying consistent with the logging style.
This change is fallout from 0af87f1
> transcode: avoid multi-line encoder configuration log
