- debian/control
Cosmetic description in Debian control file
> debian: Cosmetics in control file

- src/config.c
- src/config.h
- src/webui/comet.c
- src/webui/static/app/epg.js
- src/webui/static/app/idnode.js
- src/webui/static/app/tvheadend.js
Now is possible to write a custom mask for the dates and use the select language to make it locale depend.
> webui: Added custom date format field in config tab

- .gitignore
Just added autogenerated files to .gitignore #5064
> added generated files to .gitignore

- src/webui/static/app/idnode.js
Fixes https://tvheadend.org/issues/5126
> Fix tvheadend issue #5126 (clone button not always working as intended)

- src/descrambler/caclient.c
Fixes https://tvheadend.org/issues/5119
> Fix creation of CA Client type 'AES128 ECB Constant Code Word' (Issue #5119)

- src/webui/static/app/epg.js
This provides a simple way to provide a "now & next" view in the EPG by having a button either side of the existing "filter channel" in the EPG tab. The user can then press them to filter the EPG instead of using the drop-down.
> ui: Add Next/Prev buttons to filter epg channels.

- src/channels.c
Previously if multiple services were mapped to same channel then
we would get duplicate entries in the csv displayed at the UI in the 
drop down channel list such as a string of 'DVB-T,DVB-T,DVB-S,DVB-S'.
Now we return a unique list of 'DVB-T,DVB-S'.
> channel ui: Return unique list of services

- .doozer.json
> doozer: add missing python-requests and manually update certs for older distros

- .doozer.json
- Autobuild/cosmic-amd64.sh
- Autobuild/cosmic-i386.sh
People will no doubt ask for this.
> doozer: add cosmic cuttlefish

- src/dvr/dvr_rec.c
> dvr_rec: fix early access_destroy

- src/webui/static/app/idnode.js
- src/webui/static/app/servicemapper.js
- src/webui/static/app/status.js
Pretty much the same as master :)
> webui: more tooltips for help buttons!

- src/prop.c
- src/prop.h
> intextra: support 12bit unsigned nrs

- src/webui/extjs.c
- src/webui/static/app/ext.css
- vendor/ext-3.4.1/examples/ux/gridfilters/css/GridFilters.css
- vendor/ext-3.4.1/resources/css/structure/pivotgrid.css
> extjs: HTML and CSS fixes

- src/descrambler/descrambler.c
mpegts packet size is 188, not 128.
> Fix mpegts packet length in descrambler_data_key_check

- debian/tvheadend.service
- rpm/tvheadend.service
> systemd service file: remove wildcard mounts preventing startup - replace with a note

- src/parsers/parsers.c
variable `channel` is assigned conditionally in line 997.
> Remove dead assignment

- Makefile.hdhomerun
Note that from this version Constellation must set to AUTO to tune.
> Upgrade to libhdhomerun_20200225

- src/webui/static/app/config.js
- src/webui/static/app/idnode.js
- vendor/ext-3.4.1/resources/css/xtheme-access.css
- vendor/ext-3.4.1/resources/css/xtheme-blue.css
- vendor/ext-3.4.1/resources/css/xtheme-gray.css
* Unify css code; spaces, commas...
* Fix multiple paddings for progress bar (SNR/Signal Strength).
* Slightly increase 'TVadapters' width (design collision).
* Slightly increase 'SAT>IP Servers' width (design collision).
* ACCESS: Fix width for spinner arrows (image was repeated).
* ACCESS: Fix transparent line at bottom of not filled progress bar (SNR/Signal Strength).
> CSS: general improvements

- src/htsbuf.c
This is the patch that was tested by Ryan Li in the forum.
Let's delay adding it for a few days to see if anyone can test it with OTA data to check it doesn't break with other bad OTA data.  Ideally we'd probably split the functionality out in to a tvh_safe_utf8_strcpy and add it to all incoming data code paths (in particular incoming xmltv), but I think it's best to let it bed in for a while before doing that.
We had a string where we had a rogue byte (0x8a) which was not part of
a UTF-8 string.  This then caused some downstream parsers to abort
processing the document; other parsers ignored the bad character.
As an interim fix, we now parse the individual characters and filter
out invalid characters.  We replace such characters with a space
character (instead of a U+FFFD replacement …
> Handle bad UTF-8 in xmltv (#5909)

- src/dvr/dvr_db.c
- src/htsp_server.c
> HTSP v35: Add support for recording file size

- .doozer.json
Reverts dca46eedd9653b90d2722e67281eed0b35740730 as it's broken anyways.
> Revert dca46eedd9653b90d2722e67281eed0b35740730

- support/tvhmeta
So it should support python 2 and 3
> Changed shebang of tvhmeta to python

- src/input/mpegts/satip/satip.c
- src/input/mpegts/satip/satip_frontend.c
- src/input/mpegts/satip/satip_private.h
- src/input/mpegts/satip/satip_rtsp.c
- src/satip/rtsp.c
- src/satip/server.c
- src/satip/server.h
Added ISDB-T SATIP Support to client and server side. Tested working with networks in Brazil.
> Added ISDB-T SATIP Support

- src/input/mpegts/iptv/iptv.c
https://tvheadend.org/issues/5760
> Reset error counters for IPTV on start, issue #5760

- Makefile.hdhomerun
There is a new version of libhdhomerun
> Upgrade to libhdhomerun_20210224

- src/bouquet.c
While locking into the code, there seems to miss an else statement. The indentation seems so.
> else is missing

- src/bouquet.c
Change the format string from d to u. seen is uint32_t -> line 1192
> seen is a unsigned type

- docs/markdown/introduction.md
- docs/wizard/channels.md
- docs/wizard/channels2.md
- src/webui/static/app/tvheadend.js
See https://tvheadend.org/issues/6054
> As we no longer have access to #hts on freenode swap to using libera 

- .doozer.json
- Autobuild/bullseye-amd64.sh
- Autobuild/bullseye-arm64.sh
- Autobuild/bullseye-armel.sh
- Autobuild/bullseye-armhf.sh
- Autobuild/bullseye-i386.sh
- Autobuild/buster-arm64.sh
- Autobuild/buster-armel.sh
- Autobuild/buster-armhf.sh
- Autobuild/sid-amd64.sh
- Autobuild/sid-i386.sh
Re-do of previous PR with added extras!
> Doozer: Add more targets!

- Makefile.hdhomerun
There is a new version of libhdhomerun
> Upgrade to libhdhomerun_20210624

- src/epggrab.c
time() appears to return a slightly-rounded value as compared to
functions that return higher-precision time like gettimeofday() and
timespec_get().  Specifically, when gettimeofday() would return a
value with a low number in tv_usec, time() will return one fewer
seconds than tv_sec from gettimeofday().  The difference is minute
and probably doesn't cause an issue in most cases, but here in
epggrab.c the time of the next cron run is calculated immediately
after the previous run fires.  In this case, the value of time()
is actually one second lower than the specified cron run time. This
value is then passed into cron_multi_next(), which correctly sets
the next cron run to the current time.  Therefore, as soon as the
EPG grab completes, cron triggers again and re-runs it.  Using the
more …
> Use clock_gettime() instead of time() in epggrab.c

- src/input/mpegts/iptv/iptv.c
In iptv.c:iptv_input_is_free(), if all the conf arguments are 0
(when called from input_is_enabled()), return null if the mux
associated with the input is already running.  If the mux is
already running, starting a new input on it isn't going to create
a new input stream or break any bandwidth limit.  This fixes an
issue where starting a new channel/input on a mux that is already
active when the maximum number of input streams are in use would
result in failure.
This function is rather dense and appears to perform multiple
different functions depending on who called it, so I had a hard
time understanding exactly what is going on.  Therefore, I made
this patch in a way to be sure that it wouldn't affect how it works
in other cases than input_is_enabled().  If there is a better way
to do …
> iptv: Fix stream limit starting a new input on a running mux

- src/transcoding/codec/codecs/libs/nvenc.c
- src/transcoding/codec/internals.h
-cleanup of profiles
-include level selection for nvenc
> some changes to nvenc

- src/httpc.c
Connection header was checked for exact "close" or "upgrade" values
while it could contain multiple values delimited with commas.
New function was added for checking such cases.
Code is based on kv_find_value() function from:
https://cvsweb.openbsd.org/cgi-bin/cvsweb/src/usr.sbin/relayd/relayd.c
This fixes #6090
> httpc: Fix multi-value "Connection" header checks

- src/epggrab/module/psip.c
- Bumped up limit on number of supported EIT/ETT tables from 5 to 256 (this is the max number of EIT/ETT tables in the ATSC specification)
- Remove table type 4 as a valid ETT table, there is no support for this table here and table type 4 doesn't supply any EPG data--just long names for channels/services, etc.
- Removed the very rapid toggling between mpegts_table_{add,destroy}(...) calls on EIT/ETT tables that caused continuous enabling/disabling of EIT and ETT PIDs.
- Added an 'ETM Location' check to EIT table handling to ensure that an event's extra text is cleared in the EPG database if there is no matching ETT.
- Removed epg_broadcast_change_finish(...) because it was erasing the extra text field in EPG database when updating title in EPG database (in EIT handler).
- Added the …
> Fixed and cleanup the "PSIP: ATSC Grabber" module (Fixes #5610)

- src/input/mpegts/dvb_support.c
- Added support for decoding ATSC's "Multiple String Structure" text modes 0x1-0x6, 0x9-0x10, 0x20-0x27, 0x30-0x33.
- Convert decoded text to UTF-8 instead of ISO-8859-1.
- For unsupported 'compression types' or 'text modes' return a text string "[comptype=0x??,mode=0x??]" indicating the attempted compression type and text mode instead of the text segment.
Text output from ATSC's "Multiple String Structure" decoder should properly render in web browsers, specifically Unicode characters >= 0x80.
---
Currently, the decoder is used by tvheadend to extract:
- ATSC channel/service names encoded in VCT packets
- EPG text for the "over-the-air: PSIP: ATSC Grabber" module such as 'Title' and 'Extra text'
In Firefox, invalid UTF-8 characters are rendered as bolded '?'s and many non-English …
> Added more 'text modes' to the ATSC Multiple String Structure decoder and convert text to UTF-8. (Fixes #5162)

- Makefile
- src/muxer.h
- src/muxer/muxer_pass.c
- src/tvheadend.h
- src/tvhlog.c
- src/tvhlog.h
- src/udp.c
- src/udp.h
- src/udp_stream.c
- src/udp_stream.h
- src/webui/webui.c
- src/wrappers.c
Hi Jaroslav,
Waiting for your review ...
Stéphane Duperron
> [Feature #5723] Output UDP stream (for multicast)

- src/epg.c
- src/tcp.h
- src/webui/comet.c
- src/webui/webui.c
- src/webui/webui_api.c
- src/wizard.c
Hi,
as a maintainer I tend to dislike PRs which bundle a bunch of unrelated stuff together but… apart from the ipv6 change perhaps I guess there isn't too much to discuss about them, I assume (as I hope I didn't make some obvious errors). Feel free to cherry-pick and/or make me split it up properly.
> Misc small things: mimetypes, esoteric crash and compiler appeasement

- src/transcoding/transcode/video.c
- fixed Decoder HW + Encoder SW --> not working (with VAAPI) - Bug #6247
- fixed resize and deinterlace (*_vaapi for hw and ffmpeg for sw)
> updated function _video_filters_get_filters()

- Makefile.ffmpeg
- src/transcoding/codec.h
- src/transcoding/codec/codecs/libs/vaapi.c
- src/transcoding/transcode/hwaccels/hwaccels.c
- src/transcoding/transcode/hwaccels/hwaccels.h
- src/transcoding/transcode/hwaccels/vaapi.c
- src/transcoding/transcode/hwaccels/vaapi.h
- src/transcoding/transcode/video.c
- src/webui/static/app/codec.js
- added denoise_vaapi
- added sharpness_vaapi
> vaapi update

- src/muxer/muxer_libav.c
> update to ffmpeg codecpar

- Makefile.ffmpeg
> update NASM to 2.16.01

- src/epggrab/otamux.c
- src/tvheadend.h
Reverts tvheadend/tvheadend#1508
> Revert "fix for 64bit time_t on 32bit systems"

- src/libav.c
- src/libav.h
- src/muxer/muxer_libav.c
- migrate from AVBitStreamFilterContext to AVBSFContext
> migrate from AVBitStreamFilterContext to AVBSFContext

- Makefile.ffmpeg
> update to ffmpeg 5.1.3

- support/tvhmeta
- fixed bug with _lang3_to_lang2()  
Typo made using lang instead of lang3 in lookup map
- clean by running through autopep8
- Add more exception handling to prevent it crashing Still needs some improvements with exception types
- tidy up for pylint
- python 2 is deprecated - simplify for python 3
>  - tvhmeta: bug fixes, improve exception handling, clean up

- .doozer.json
- .github/workflows/build.yml
I'm not sure whether Doozer is still relevant, now that RPMFusion is shipping rather recent versions.
> Update config for Fedora 37/38

- src/config.c
- src/config.h
- src/dvr/dvr_config.c
- src/settings.c
- src/settings.h
- vendor/xdg-user-dirs/xdg-user-dir-lookup.c
This series adds support for the [XDG spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).
> Add XDG support

- src/input/mpegts/tvhdhomerun/tvhdhomerun_frontend.c
Removed nested function 'appendPidRange' from within function 'tvhdhomerun_frontend_update_pids' and converted it to a normal function 'tvhdhomerun_frontend_update_pids_appendPidRange'.
Nested functions are a non-standard extension to C that may only be supported by the gcc compiler.  After all, there are other compilers.
Manually unwrapped the nested function and it looks a little uglier.  There should be no change to the functionality, excepting standard C code compliance.  I promise to never use a nested function again!
Verification:
- tested streaming/recording of programs still works.
- checked the hdhomeruns list of PIDs filter (via: hdhomerun .... get /tuner?/filter) in various situations is correct.
While this is a very simple change, please feel free to let me know of a better …
> Removed nested function 'appendPidRange'

- Makefile.ffmpeg
- src/transcoding/transcode/hwaccels/vaapi.c
- updates ffmpeg to 6.0.1
- updates x264 to latest
- updates libvpx to 1.13.1
supersedes #1522 
it builds, otherwise I can't really test it
> ffmpeg update to 6.0.1

- src/webui/extjs.c
As well as (perhaps) a minor improvement, this changes one of the strings that ripples through to Transifex. It will confirm how automated the process is, in that direction at least (i.e. is it automated through URL origin tracking, or manual).
> WebUI: Update donation string as a test to Transifex feed

- Makefile.ffmpeg
FFNVCODEC_VER  = 11.1.5.0 -> 12.1.14.0
> Makefile.ffmpeg nvenc update

- Makefile.ffmpeg
> update to ffmpeg 6.1.1

- .github/ISSUE_TEMPLATE/bug_report.yml
> templates: add log section to bug_report.yml

- src/timeshift/private.h
- src/timeshift/timeshift_writer.c
> Fix audio-only timeshift memory usage

- .github/workflows/build-cloudsmith.yml
- Autobuild/identify-os.sh
- support/cloudsmith.sh
Per discussion on IRC and Discord.
This change requires adding three repository variables:
`CLOUDSMITH_ORG`
`CLOUDSMITH_OWNER`
`CLOUDSMITH_REPO`
> ci: use CURL for cloudsmith.sh and enable RPM upload

- src/webui/static/app/tvheadend.js
Squashed and rebased version of #1528 from @pmatis
> Add support for 12-hour custom date formats

- src/spawn.c
> Make sure we spawn the best matching executable and not the first matcb

- Makefile.ffmpeg
- support/patches/fix_id_1841.patch
> update to libvpx 1.14.0

- Autobuild/armv6l.sh
> Create special tvheadend-armv6l and tvheadend-dbg-armv6l packages

- support/version
> Fix detection of unknown version numbers in support/version

- src/webui/webui.c
Squashed and reworded version of #1381
> Correct M3U playlist logo tag

- src/http.c
> Remove useless NULL-assignment in http.c

- src/ratinglabels.c
> Remove useless NULL-check in ratinglabels.c

- debian/tvheadend.postrm
This fixes #1722 on my test system.
> Remove tvheadend user on purge

- src/config.c
- src/config.h
- src/idnode.c
- src/main.c
- src/prop.c
- src/prop.h
- src/transcoding/codec.h
- src/transcoding/codec/codec.c
- src/transcoding/codec/codecs/libs/vaapi.c
- src/transcoding/codec/internals.h
- src/transcoding/codec/module.c
- src/transcoding/codec/profile_video_class.c
- src/transcoding/codec/vainfo.c
- src/transcoding/codec/vainfo.h
- src/tvhlog.c
- src/tvhlog.h
- src/webui/static/app/codec.js
> Merge #1531

- src/htsp_server.c
For upcoming Kodi v22 support for "PVR Providers" I need the service provider for a channel exposed via HTSP. Thanks.
> HTSP: Expose service provider name with channel information.

- src/bouquet.c
The following pull request introduced a feature I've been after for many years - allowing multiple network bouquets to have their channels merged together: [#1273](https://github.com/tvheadend/tvheadend/pull/1273)
Since setting this up I noticed a problem when a service is removed (either manually or when the bouquet refreshes); whereby the channel is also removed even if it has other services attached from the same Tvheadend network global bouquet.
As an example, Channel 4 has multiple regional variations, so I tried to disable those that were not for my region. But after disabling just one service it deleted the channel - as illustrated in the following video:
https://github.com/user-attachments/assets/f39ca865-e399-4ab4-90d9-9194734d310f
Even worse, this caused all the serieslink …
> bouquet: fix overzealous channel removals in merged multi-network setup

- src/epggrab.c
> fixes #1733

- src/htsp_server.c
Currently, all HTSP client versions only receive rating label fields if rating labels are enabled within TVH.  Older clients are also 'protected' from receiving rating label fields using the client preferred protocol version number exchanged during the session handshake.
This is not in keeping with the original intent of the protocol version numbering scheme whereby only changes to existing fields needed to be controlled via versioning, not the presence of new fields.
This PR removes all version-dependent tests relating to rating labels from HTSP and provides all rating label fields regardless of the client version.  It should be noted that if rating label processing is not enabled in TVH, no rating label fields will be provided via HTSP regardless of the client version.
Following the …
> Remove HTSP client version tests for rating labels and string UUIDs

- src/config.c
- src/config.h
- src/input/mpegts/iptv/iptv_rtcp.c
- src/input/mpegts/iptv/iptv_rtsp.c
- src/input/mpegts/iptv/iptv_udp.c
- src/input/mpegts/satip/satip_frontend.c
- src/satip/rtsp.c
- src/udp.c
- src/udp.h
- src/upnp.c
- src/webui/webui.c
Here is the associated feature request with explanations: #1738
> iptv: allow to limit UDP ports for unicast inputs

- Makefile.ffmpeg
- support/patches/libx265-substring.patch
See https://github.com/tvheadend/tvheadend/pull/1797#issuecomment-2869611972
> Fix: allow x265 build on CMake <3.2

- src/transcoding/codec.h
- src/transcoding/codec/internals.h
- src/transcoding/codec/profile.c
- src/transcoding/codec/profile_video_class.c
- src/transcoding/transcode/stream.c
- src/webui/static/app/codec.js
- allow NVENC, VAAPI and MMAL to coexist in the same build.
- give the user the capability for force hw decoder or to match the hw decoder with hw encoder
> allow NVENC, VAAPI and MMAL to coexist in the same build

- src/prop.c
PT_DYN_INT should be read and write as int (32 bits)
> fix read/write of PT_DYN_INT

- src/input/mpegts/iptv/iptv_http.c
Not too generic, but for my use case it works better than the main branch.
before:
```
2024-08-26 09:46:17.477 [   INFO] mpegts: rai.m3u - [3] Rai 3 in IPTV Automatic Network - tuning on IPTV #1
2024-08-26 09:46:17.568 [   INFO] subscription: 0001: "HTTP" subscribing to mux "rai.m3u - [3] Rai 3", weight: 10, adapter: "IPTV #1", network: "IPTV Automatic Network", service: "Raw PID Subscription", hostname="192.168.59.199", client="VLC/3.0.20 LibVLC/3.0.20"
2024-08-26 09:46:18.276 [  DEBUG] iptv: HLS - selected stream 1280x720, 2727kb/s, avc1.77.41,mp4a.40.2
2024-08-26 09:46:18.276 [  TRACE] iptv: m3u url: 'https://streamcdnl6-8e7439fdb1694c8da3a0fd63e4dda518.msvdn.net/raitre1/hls/rai3_2400/chunklist.m3u8?baseuri=%2Fraitre1%2Fhls%2F&tstart=0&tend=1724748557&tk2=f68c6a7151a47c7057653f0908de7c9 …
```
> iptv: handle relative key URL

- src/transcoding/transcode/stream.c
- video hw accel should only be applied for video streams
Fixes: #1827
> fix bug 1827: video hw accel should only be applied for video streams

- src/muxer/muxer_mkv.c
Change the ‘LAW_RATING’ tag to contain the ‘rl_display_label’ field augmented with either the ‘rl_country’ field or the ‘rl_authority’ field rather than the age.  Eg: ‘PG (AUS)’ or ‘PG (ACMA)’
Add the ‘SUBTITLE’ tag when the appropriate EPG field is available.
Add the ‘COMMENT’ tag when the appropriate DVR entry field is available.
Add some comments to existing code regarding MKV tag values in use.
> MKV Tags - Change rating label.  Add Sub-title and Comment.

- src/muxer.h
- src/muxer/muxer_libav.c
- src/profile.c
- src/transcoding/transcode/transcoder.c
- src/webui/static/app/profile.js
- add service_name, service_provider, mpegts_transport_id, mpegts_service_type, mpegts_pmt_start_pid, mpegts_start_pid, mpegts_service_id, mpegts_original_service_id
> add mpegts parameters from input stream

- src/epggrab.c
Resolution for Coverity CID 552897.
- Encase mux scheduler read operation in a mutex lock/unlock transaction.
> Coverity CID 552897

- CONTRIBUTING.md
- README.md
This PR does some overdue cleanup, simplification, and minor wordsmithing on the README and CONTRIBUTING files. Use the links below for easier review:
* README https://github.com/chewitt/tvheadend/tree/cleanup
* CONTRIBUTING https://github.com/chewitt/tvheadend/blob/cleanup/CONTRIBUTING.md
> repo: cleanup README.md/CONTRIBUTING.md files

- src/transcoding/transcode/hwaccels/vaapi.c
- fix memory leak 3 - transcoding
> fix memory leak 3 - transcoding

- README.md
Add note about running `sudo make install` to the Linux build section of the README.
> Add 'sudo make install' to the Linux build notes.
